# Generated by Django 2.2.9 on 2020-07-14 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suggestions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300,
                        null=True,
                        verbose_name="Title, type, domain od propossed data",
                    ),
                ),
                ("notes", models.TextField(null=True, verbose_name="Data description")),
                (
                    "organization_name",
                    models.CharField(max_length=100, null=True, verbose_name="Institution name"),
                ),
                (
                    "data_link",
                    models.URLField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Link to data",
                    ),
                ),
                (
                    "potential_possibilities",
                    models.TextField(null=True, verbose_name="Indicate potential possibilities"),
                ),
                ("comment", models.TextField(null=True, verbose_name="Comment")),
                (
                    "submission_date",
                    models.DateField(null=True, verbose_name="Submission date"),
                ),
                (
                    "decission",
                    models.CharField(
                        choices=[
                            ("examined", "Examined"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="examined",
                        max_length=10,
                        verbose_name="Decission",
                    ),
                ),
                (
                    "decission_date",
                    models.DateField(null=True, verbose_name="Decission date"),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="datasets_proposed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported by",
                    ),
                ),
            ],
        ),
    ]
