# Generated by Django 2.2.9 on 2020-07-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0002_datasetsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetsubmission",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="datasetsubmission",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Institution name"),
        ),
        migrations.AlterField(
            model_name="datasetsubmission",
            name="potential_possibilities",
            field=models.TextField(blank=True, null=True, verbose_name="Indicate potential possibilities"),
        ),
    ]
