# Generated by Django 2.2.14 on 2020-07-17 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0004_auto_20200716_1601"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptedDatasetSubmission",
            fields=[],
            options={
                "verbose_name": "Accepted dataset submission",
                "verbose_name_plural": "Accepted dataset submissions",
                "ordering": ("-submission_date",),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("suggestions.datasetsubmission",),
        ),
        migrations.AlterModelOptions(
            name="datasetsubmission",
            options={
                "ordering": ("-submission_date",),
                "verbose_name": "Dataset submission",
                "verbose_name_plural": "Dataset submissions",
            },
        ),
    ]
