# Generated by Django 2.2.14 on 2020-07-21 05:44

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
import modeltrans.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0006_auto_20200717_1224"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="datasetsubmission",
            managers=[
                ("raw", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="i18n",
            field=modeltrans.fields.TranslationField(fields=("slug",), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="published_at",
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor="status", when={"published"}),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="removed_at",
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor="is_removed", when={True}),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="slug",
            field=models.SlugField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[(0, "dummy")],
                default="published",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="datasetsubmission",
            name="decision",
            field=models.CharField(
                choices=[
                    ("examined", "Examined"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="examined",
                max_length=10,
                verbose_name="Decision",
            ),
        ),
        migrations.AlterField(
            model_name="datasetsubmission",
            name="decision_date",
            field=models.DateField(null=True, verbose_name="Decision date"),
        ),
    ]
