# Generated by Django 2.2.14 on 2020-07-21 12:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0007_auto_20200721_0744"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetSubmissionTrash",
            fields=[],
            options={
                "verbose_name": "Trash",
                "verbose_name_plural": "Trash",
                "ordering": ("-submission_date",),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("suggestions.datasetsubmission",),
            managers=[
                ("raw", django.db.models.manager.Manager()),
            ],
        ),
    ]
