# Generated by Django 2.2.14 on 2020-07-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0008_datasetsubmissiontrash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetsubmission",
            name="decision",
            field=models.CharField(
                choices=[
                    ("examined", "--------"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="examined",
                max_length=10,
                verbose_name="Decision",
            ),
        ),
    ]
