# Generated by Django 2.2.9 on 2020-07-29 13:13
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0013_auto_20200729_1439"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-410-suggestions-datasetsubmission-history_other.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-410-suggestions-datasetsubmission-history_other_backward.sql",
                )
            ).read(),
        )
    ]
