# Generated by Django 2.2.9 on 2020-07-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0014_datasetsubmission_history_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetsubmission",
            name="potential_possibilities",
            field=models.TextField(blank=True, verbose_name="provide potential data use"),
        ),
    ]
