# Generated by Django 2.2.9 on 2020-07-31 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mcod.core.db.mixins
import model_utils.fields
import modeltrans.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suggestions", "0015_auto_20200730_1056"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AcceptedDatasetSubmission",
        ),
        migrations.AlterModelOptions(
            name="datasetsubmissiontrash",
            options={
                "default_manager_name": "objects",
                "ordering": ("-submission_date",),
                "verbose_name": "Trash",
                "verbose_name_plural": "Trash",
            },
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="datasetsubmissions_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="datasetsubmission",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="datasetsubmissions_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modified by",
            ),
        ),
        migrations.AlterField(
            model_name="datasetsubmission",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="datasetsubmissions_submitted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reported by",
            ),
        ),
        migrations.CreateModel(
            name="AcceptedDatasetSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, max_length=600)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "removed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        when={True},
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "title",
                    models.CharField(
                        max_length=300,
                        verbose_name="Title, type, domain od propossed data",
                    ),
                ),
                ("notes", models.TextField(verbose_name="Data description")),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Institution name"),
                ),
                (
                    "data_link",
                    models.URLField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Link to data",
                    ),
                ),
                (
                    "potential_possibilities",
                    models.TextField(blank=True, verbose_name="provide potential data use"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "submission_date",
                    models.DateField(null=True, verbose_name="Submission date"),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accepted", "Proposal accepted"),
                            ("rejected", "Proposal rejected"),
                        ],
                        max_length=8,
                        verbose_name="decision",
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(null=True, verbose_name="Decision date"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(fields=("slug",), required_languages=(), virtual_fields=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accepteddatasetsubmissions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accepteddatasetsubmissions_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accepteddatasetsubmissions_submitted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reported by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset submission",
                "verbose_name_plural": "Dataset submissions",
                "ordering": ("-submission_date",),
                "abstract": False,
                "default_manager_name": "objects",
            },
            bases=(
                mcod.core.db.mixins.AdminMixin,
                mcod.core.db.mixins.ApiMixin,
                models.Model,
            ),
        ),
    ]
