# Generated by Django 2.2.9 on 2020-08-03 09:58
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0017_datasetsubmission_accepted_dataset_submission"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-410-suggestions-accepteddatasetsubmission-history_other.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-410-suggestions-accepteddatasetsubmission-history_other_backward.sql",
                )
            ).read(),
        )
    ]
