# Generated by Django 2.2.9 on 2020-08-05 14:19
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "suggestions",
            "0020_datasetcomment_datasetcommenttrash_resourcecomment_resourcecommenttrash",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-410-suggestions-datasetcomment-history_other.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-410-suggestions-datasetcomment-history_other_backward.sql",
                )
            ).read(),
        )
    ]
