# Generated by Django 2.2.9 on 2020-08-05 14:25
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0021_datasetcomment_history_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-410-suggestions-resourcecomment-history_other.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-410-suggestions-resourcecomment-history_other_backward.sql",
                )
            ).read(),
        )
    ]
