# Generated by Django 2.2.9 on 2020-08-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0022_resourcecomment_history_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="accepteddatasetsubmission",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="proposal active"),
        ),
    ]
