# Generated by Django 2.2.9 on 2020-08-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0023_accepteddatasetsubmission_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accepteddatasetsubmission",
            options={
                "default_manager_name": "objects",
                "ordering": ("-submission_date",),
                "verbose_name": "Accepted dataset submission",
                "verbose_name_plural": "Accepted dataset submissions",
            },
        ),
        migrations.AlterModelOptions(
            name="datasetsubmissiontrash",
            options={
                "default_manager_name": "objects",
                "ordering": ("-submission_date",),
                "verbose_name": "Dataset submission - Trash",
                "verbose_name_plural": "Dataset submissions - Trash",
            },
        ),
    ]
