# Generated by Django 2.2.9 on 2020-08-11 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suggestions", "0024_auto_20200810_0922"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opinion",
                    models.CharField(
                        choices=[("plus", "Like"), ("minus", "Dislike")],
                        default="plus",
                        max_length=6,
                        verbose_name="Feedback",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="feedback",
                        to="suggestions.AcceptedDatasetSubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
