# Generated by Django 2.2.9 on 2020-10-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0026_auto_20200812_0957"),
    ]

    operations = [
        migrations.AddField(
            model_name="accepteddatasetsubmission",
            name="is_published_for_all",
            field=models.BooleanField(default=False, verbose_name="publish for all users"),
        ),
    ]
