# Generated by Django 2.2.9 on 2020-12-14 06:37

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0027_accepteddatasetsubmission_is_published_for_all"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accepteddatasetsubmission",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=(
                    "title",
                    "notes",
                    "organization_name",
                    "potential_possibilities",
                    "slug",
                ),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
