# Generated by Django 2.2.9 on 2021-05-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0030_auto_20210517_1732"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="submissionfeedback",
            managers=[],
        ),
    ]
