# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0032_auto_20210622_1346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accepteddatasetsubmission",
            name="comment",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="datasetcomment",
            name="comment",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="datasetcomment",
            name="editor_comment",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="datasetsubmission",
            name="comment",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="resourcecomment",
            name="comment",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="resourcecomment",
            name="editor_comment",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="notes",
            field=mcod.lib.model_sanitization.SanitizedTextField(),
        ),
    ]
