# Generated by Django 2.2.9 on 2020-05-28 11:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mcod.core.db.mixins
import mcod.core.storages
import model_utils.fields
import modeltrans.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, max_length=600)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "removed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        when={True},
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=300, verbose_name="title")),
                ("notes", models.TextField(verbose_name="description")),
                ("venue", models.CharField(max_length=300, verbose_name="venue")),
                (
                    "participants_number",
                    models.PositiveIntegerField(verbose_name="number of participants"),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=2000,
                        storage=mcod.core.storages.CourseStorage(base_url=None, location=None),
                        upload_to="%Y%m%d",
                        verbose_name="file",
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(fields=("slug",), required_languages=(), virtual_fields=True),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "default_manager_name": "objects",
            },
            bases=(mcod.core.db.mixins.ApiMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, max_length=600)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "removed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        when={True},
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("general", "academy course module type"),
                            ("technical", "Technical"),
                            ("law", "Law"),
                            ("extra", "Extra"),
                            ("exam", "Exam"),
                        ],
                        max_length=9,
                        verbose_name="module type",
                    ),
                ),
                ("start", models.DateField(verbose_name="start date")),
                ("end", models.DateField(verbose_name="end date")),
                (
                    "number_of_days",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="number of days",
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(fields=("slug",), required_languages=(), virtual_fields=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="academy.Course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "course module",
                "verbose_name_plural": "course modules",
                "default_manager_name": "objects",
            },
            bases=(mcod.core.db.mixins.ApiMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CourseTrash",
            fields=[],
            options={
                "verbose_name": "Trash (Courses)",
                "verbose_name_plural": "Trash (Courses)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("academy.course",),
        ),
    ]
