# Generated by Django 2.2.9 on 2020-05-26 11:17
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(os.path.join(settings.DATABASE_DIR, "ODSOFT-100-academy-course-history_other.sql")).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-100-academy-course-history_other_backward.sql",
                )
            ).read(),
        )
    ]
