# Generated by Django 2.2.9 on 2020-06-02 11:54

from django.db import migrations, models
import mcod.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_course_history_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="materials_file",
            field=models.FileField(
                blank=True,
                max_length=2000,
                null=True,
                storage=mcod.core.storages.CourseMaterialsStorage(base_url=None, location=None),
                upload_to="%Y%m%d",
                verbose_name="materials file",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=2000,
                null=True,
                storage=mcod.core.storages.CourseStorage(base_url=None, location=None),
                upload_to="%Y%m%d",
                verbose_name="schedule file",
            ),
        ),
    ]
