# Generated by Django 2.2.9 on 2020-07-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_auto_20200630_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemodule",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "academy course module type"),
                    ("technical", "Technical"),
                    ("law", "Law"),
                    ("law_technical", "Law/Technical"),
                    ("extra", "Extra"),
                    ("exam", "Exam"),
                ],
                max_length=13,
                verbose_name="module type",
            ),
        ),
    ]
