# Generated by Django 2.2.9 on 2021-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_auto_20200701_1234"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coursemodule",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
    ]
