# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_auto_20210423_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="notes",
            field=mcod.lib.model_sanitization.SanitizedTextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="course",
            name="venue",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300, verbose_name="venue"),
        ),
    ]
