# Generated by Django 2.0 on 2018-04-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("licenses", "0001_initial"),
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="licenses.License",
                verbose_name="License ID",
            ),
        ),
    ]
