# Generated by Django 2.0.4 on 2018-08-20 09:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_auto_20180611_2234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="notes",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="Notes"),
        ),
    ]
