# Generated by Django 2.0.4 on 2018-10-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_auto_20180820_1154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=600, unique=True, verbose_name="Slug"),
        ),
    ]
