# Generated by Django 2.0.4 on 2019-02-05 11:15
import os
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_internals"),
        ("articles", "0009_create_article_category_model_and_relation_from_article"),
    ]

    operations = [
        migrations.RunSQL(open(os.path.join(settings.DATABASE_DIR, "patches/005-tg-article-history.sql")).read()),
        migrations.RunSQL(open(os.path.join(settings.DATABASE_DIR, "MCOD-1268-split-knowledge-base-and-news.sql")).read()),
    ]
