# Generated by Django 2.0.4 on 2019-02-07 13:09

import django.contrib.postgres.indexes
from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_auto_20190206_2018"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecategory",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name", "description"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AddIndex(
            model_name="articlecategory",
            index=django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="article_cat_i18n_d230a5_gin"),
        ),
    ]
