# Generated by Django 2.1.4 on 2019-02-25 09:57

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_auto_20190207_1409"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("slug", "title", "notes"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
