# Generated by Django 2.2.9 on 2020-02-17 08:44

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_auto_20190604_2022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecategory",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name", "description", "slug"),
                required_languages=("pl",),
                virtual_fields=True,
            ),
        ),
    ]
