# Generated by Django 2.2.9 on 2020-11-27 12:14

from django.db import migrations
import mcod.lib.widgets


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0019_articlecategory_type_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="notes",
            field=mcod.lib.widgets.RichTextUploadingField(null=True, verbose_name="Notes"),
        ),
    ]
