# Generated by Django 2.2.9 on 2021-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0020_auto_20201127_1314"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="articlecategory",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
    ]
