# Generated by Django 2.0.4 on 2018-05-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTrash",
            fields=[],
            options={
                "verbose_name": "Trash",
                "verbose_name_plural": "Trash",
                "proxy": True,
                "indexes": [],
            },
            bases=("categories.category",),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "default_manager_name": "objects",
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
