# Generated by Django 2.0.4 on 2019-02-05 08:02

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_auto_20180525_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="i18n",
            field=modeltrans.fields.TranslationField(fields=("title",), required_languages=(), virtual_fields=True),
        ),
    ]
