# Generated by Django 2.0.4 on 2019-02-05 08:04

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_category_i18n"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="category_i18n_fff46e_gin"),
        ),
    ]
