# Generated by Django 2.0.4 on 2019-02-05 08:31

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0005_auto_20190205_0904"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("title", "slug", "description"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
