# Generated by Django 2.2.9 on 2020-12-27 19:37

from django.db import migrations
from django.utils.text import slugify

NEW_CATEGORIES_DATA = [
    {
        "code": "AGRI",
        "title": "Rolnictwo, rybołówstwo, leśnictwo i żywność",
        "title_en": "Agriculture, fisheries, forestry and food",
        "description_en": "This concept identifies datasets covering such domains as agriculture, fisheries, forestry or food. Agriculture is the science and art of cultivating plants and livestock. Fisheries are activities leading to harvesting of fish; may involve capture of wild fish or raising of fish through aquaculture. Forestry is the science and craft of creating, managing, using, conserving and repairing forests, woodlands and associated resources for human and environmental benefits. Food is any substance consumed to provide nutritional support for an organism. Dataset examples: Agricultural and Vegetable Catalogue; The Community Fishing Fleet Register; Pan-European Map of Forest Biomass Increment; Food composition database for nutrient intake: selected vitamins and minerals in selected European countries.",
    },
    {
        "code": "EDUC",
        "title": "Edukacja, kultura i sport",
        "title_en": "Education, culture and sport",
        "description_en": "This concept identifies datasets covering such domains as education, culture or sport. Education is the process of facilitating learning, or the acquisition of knowledge, skills, values, beliefs and habits. Culture encompasses the social behavior and norms found in human societies, as well as the knowledge, beliefs, arts, laws, customs, capabilities and habits of the individuals in these groups. Sport includes all forms of competitive physical activity or games which maintain or improve physical ability and skills while providing enjoyment to participants, and in some cases, entertainment for spectators. Dataset examples: European Skills, Competences, Qualifications and Occupations (ESCO); EU Member States and international human rights obligations; Participation in any cultural or sport activities in the last 12 months by sex, age and educational attainment level.",
    },
    {
        "code": "ENVI",
        "title": "Środowisko",
        "title_en": "Environment",
        "description_en": "This concept identifies datasets covering the domain of environment. The natural environment encompasses the interaction of all living species, climate, weather and natural resources that affect human survival and economic activity. Dataset examples: Attitudes of European citizens towards the environment; Pollutant emissions from transport.",
    },
    {
        "code": "ENER",
        "title": "Energia",
        "title_en": "Energy",
        "description_en": "This concept identifies datasets covering the domain of energy. Energy is the quantitative property that must be transferred to an object in order to perform work on, or to heat, the object. Living organisms require energy to stay alive; human civilisation requires energy to function. Dataset examples: European gas market reports; Electricity prices by type of user.",
    },
    {
        "code": "TRAN",
        "title": "Transport",
        "title_en": "Transport",
        "description_en": "This concept identifies datasets covering the domain of transport. Transport is the movement of humans, animals and goods from one location to another. Modes of transport include air, land (rail and road), water, cable, pipeline and space. Dataset examples: Total length of motorways; Airport traffic data by reporting airport and airlines.",
    },
    {
        "code": "TECH",
        "title": "Nauka i technologia",
        "title_en": "Science and technology",
        "description_en": "This concept identifies datasets covering such domains as science or technology. Science is a systematic enterprise that builds and organises knowledge in the form of testable explanations and predictions. Modern science is typically divided into three major branches that consist of the natural sciences, which study nature in the broadest sense; the social sciences, which study individuals and societies; and the formal sciences, which study abstract concepts. Technology is the sum of techniques, skills, methods and processes used in the production of goods or services or in the accomplishment of objectives, such as scientific investigation. Dataset examples: CORDIS - EU research projects under Horizon 2020 (2014-2020); Take-up of mobile broadband (subscriptions/100 people).",
    },
    {
        "code": "ECON",
        "title": "Gospodarka i finanse",
        "title_en": "Economy and finance",
        "description_en": "This concept identifies datasets covering such domains as economy or finance. Economy is the area of the production, distribution and trade, as well as consumption of goods and services by different agents. In its broadest sense, the economy is defined as a social domain that emphasize the practices, discourses and material expressions associated with the production, use, and management of resources. Finance is the study of money and how it is used. Specifically, it deals with the questions of how an individual, company or government acquires the money needed and how they then spend or invest that money. Dataset examples: Tenders Electronic Daily (TED) - public procurement notices from the EU and beyond; General government deficit (-) and surplus (+) - quarterly data.",
    },
    {
        "code": "SOCI",
        "title": "Ludność i społeczeństwo",
        "title_en": "Population and society",
        "description_en": "This concept identifies datasets covering such domains as population or society. Population is a collection of humans and their entire race; it is the number of people in a city or town, region, country or world. A society is a group of individuals involved in persistent social interaction, or a large social group sharing the same spatial or social territory, typically subject to the same political authority and dominant cultural expectations. Dataset examples: Population density by NUTS 2 region; Violence against Women: An EU-wide survey.",
    },
    {
        "code": "HEAL",
        "title": "Zdrowie",
        "title_en": "Health",
        "description_en": "This concept identifies datasets covering the domain of health. Health is a state of physical, mental and social well-being in which disease and infirmity are absent. Dataset examples: COVID-19 Coronavirus data; European Cancer Information System.",
    },
    {
        "code": "GOVE",
        "title": "Rząd i sektor publiczny",
        "title_en": "Government and public sector",
        "description_en": "This concept identifies datasets covering such domains as government or public sector. A government is the system or group of people governing an organised community, often a state. The public sector is the part of the economy composed of both public services and public enterprises. Public sector services and enterprises can be controlled by central government, regional or local authorities. Organisations that are not part of the public sector are either a part of the private sector or voluntary sector. Dataset examples: Candidate countries and potential candidates: Government statistics; Transparency Register.",
    },
    {
        "code": "REGI",
        "title": "Regiony i miasta",
        "title_en": "Regions and cities",
        "description_en": "This concept identifies datasets covering such domains as regions or cities. In the field of political geography, regions tend to be based on political units such as sovereign states; subnational units such as administrative regions, provinces, states, counties, townships, territories, etc.; and multinational groupings. A city is a large human settlement. Dataset examples: NUTS - Nomenclature of territorial units for statistics classification; UDP - GDP per capita by metro regions, 2000 - 2060.",
    },
    {
        "code": "JUST",
        "title": "Sprawiedliwość, ustrój sądów i bezpieczeństwo publiczne",
        "title_en": "Justice, legal system and public safety",
        "description_en": "This concept identifies datasets covering such domains as justice, legal system or public safety. Justice includes both the attainment of that which is just and the philosophical discussion of that which is just; here it mainly means the procedural justice as found in the study and application of the law. The contemporary legal systems of the world are generally based on one of four basic systems: civil law, common law, statutory law, religious law or combinations of these. Public safety is the function of governments which ensures the protection of citizens, persons in their territory, organisations and institutions against threats to their well-being – and to the prosperity of their communities. Dataset examples: EU case-law; Information on Member States Law; European Data Protection Supervisor register of processing operations.",
    },
    {
        "code": "INTR",
        "title": "Kwestie międzynarodowe",
        "title_en": "International issues",
        "description_en": "This concept identifies datasets covering the domain of international issues. An issue – important topic or problem for debate or discussion – is international when the participants represent at least two countries. Dataset examples: Consolidated list of persons, groups and entities subject to EU financial sanctions; European Commission — DG DEVCO – development and humanitarian assistance to Afghanistan.",
    },
]


def create_basic_dcat_categories(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    for data in NEW_CATEGORIES_DATA:
        try:
            category = Category.objects.get(code=data["code"])
            print("DID NOT CREATE: ", end="")
        except Category.DoesNotExist:
            title_en = data.pop("title_en")
            data["i18n"] = {
                "title_en": title_en,
                "description_en": data.pop("description_en"),
                "slug_en": slugify(title_en),
            }
            data["slug"] = slugify(data["title"])

            category = Category(**data)
            category.save()
            print("CREATED: ", end="")

        print(f"Category <code: {category.code}, title: {category.title}>")


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0010_category_code"),
    ]

    operations = [
        migrations.RunPython(create_basic_dcat_categories),
    ]
