# Generated by Django 2.2.9 on 2021-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_datamigration_create_basic_dcat_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
    ]
