# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0012_category_is_permanently_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=100, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=mcod.lib.model_sanitization.SanitizedTextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="i18n",
            field=mcod.lib.model_sanitization.SanitizedTranslationField(
                fields=("title", "description", "slug"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=100, verbose_name="Title"),
        ),
    ]
