# Generated by Django 2.2.9 on 2020-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_auto_20201016_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="period_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="period name"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
    ]
