# Generated by Django 2.2.9 on 2020-11-30 09:48

from django.db import migrations


def update_schedule_from_period(apps, schema_editor):
    schedule_model = apps.get_model("schedules", "Schedule")
    for obj in schedule_model.objects.all():
        start_date = obj.period.start_date
        obj.start_date = start_date
        obj.period_name = "%(part)s półrocze %(year)s" % {
            "part": "I" if start_date.month in range(1, 7) else "II",
            "year": start_date.year,
        }
        obj.save()


def reverse_update_schedule_from_period(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_auto_20201130_1044"),
    ]

    operations = [
        migrations.RunPython(update_schedule_from_period, reverse_update_schedule_from_period),
    ]
