# Generated by Django 2.2.9 on 2020-11-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_update_schedule_from_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="period",
        ),
    ]
