# Generated by Django 2.2.9 on 2020-11-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_remove_schedule_period"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Period",
        ),
    ]
