# Generated by Django 2.2.9 on 2020-12-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_delete_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userscheduleitem",
            name="is_openness_score_increased",
            field=models.NullBooleanField(verbose_name="is openness score increased?"),
        ),
        migrations.AlterField(
            model_name="userscheduleitem",
            name="is_quality_improved",
            field=models.NullBooleanField(verbose_name="is quality improved?"),
        ),
    ]
