# Generated by Django 2.2.9 on 2020-12-07 08:16
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0007_auto_20201203_1310"),
    ]

    operations = [TrigramExtension()]
