# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0010_auto_20210423_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=255),
        ),
    ]
