# Generated by Django 2.2.9 on 2021-07-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0007_object_pk_type"),
        ("histories", "0004_apply_patches"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[],
            options={
                "verbose_name": "History",
                "verbose_name_plural": "Histories",
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auditlog.logentry",),
        ),
    ]
