# Generated by Django 2.2.9 on 2021-10-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histories", "0005_logentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntryIndexSync",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_indexed", models.DateTimeField()),
            ],
        ),
    ]
