# Generated by Django 2.2.9 on 2021-10-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("histories", "0006_logentryindexsync"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogEntryIndexSync",
        ),
    ]
