# Generated by Django 2.2.9 on 2022-05-19 10:32
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("histories", "0007_delete_logentryindexsync"),
    ]

    operations = [
        migrations.RunSQL(
            open(os.path.join(settings.DATABASE_DIR, "ODSOFT-2595-drop-history.sql")).read(),
            reverse_sql=open(os.path.join(settings.DATABASE_DIR, "ODSOFT-2595-drop-history-backward.sql")).read(),
        )
    ]
