# Generated by Django 2.2.9 on 2022-06-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("histories", "0008_auto_20220519_1232"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoryIndexSync",
        ),
    ]
