# Generated by Django 2.2.9 on 2020-12-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0030_auto_20200910_1117"),
    ]

    operations = []
