# Generated by Django 2.2.9 on 2021-12-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcases", "0002_auto_20211213_2350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcase",
            name="category",
            field=models.CharField(
                choices=[
                    ("app", "Application"),
                    ("www", "Website"),
                    ("other", "Other"),
                ],
                max_length=5,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="category",
            field=models.CharField(
                choices=[
                    ("app", "Application"),
                    ("www", "Website"),
                    ("other", "Other"),
                ],
                max_length=5,
                verbose_name="category",
            ),
        ),
    ]
