# Generated by Django 2.2.9 on 2024-10-29 14:08

import django.contrib.postgres.fields
from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("showcases", "0006_auto_20220204_1511"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcase",
            name="author",
            field=mcod.lib.model_sanitization.SanitizedCharField(blank=True, max_length=50, null=True, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="showcase",
            name="external_datasets",
            field=mcod.lib.model_sanitization.SanitizedJSONField(
                blank=True, default=list, null=True, verbose_name="external datasets"
            ),
        ),
        migrations.AlterField(
            model_name="showcase",
            name="i18n",
            field=mcod.lib.model_sanitization.SanitizedTranslationField(
                fields=("title", "notes", "image_alt", "illustrative_graphics_alt", "slug"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AlterField(
            model_name="showcase",
            name="illustrative_graphics_alt",
            field=mcod.lib.model_sanitization.SanitizedCharField(
                blank=True, max_length=255, verbose_name="illustrative graphics alternative text"
            ),
        ),
        migrations.AlterField(
            model_name="showcase",
            name="image_alt",
            field=mcod.lib.model_sanitization.SanitizedCharField(
                blank=True, max_length=255, null=True, verbose_name="Alternative text"
            ),
        ),
        migrations.AlterField(
            model_name="showcase",
            name="notes",
            field=mcod.lib.model_sanitization.SanitizedTextField(null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="showcase",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="author",
            field=mcod.lib.model_sanitization.SanitizedCharField(blank=True, max_length=50, null=True, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="comment",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="external_datasets",
            field=mcod.lib.model_sanitization.SanitizedJSONField(
                blank=True, default=list, null=True, verbose_name="external datasets"
            ),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=mcod.lib.model_sanitization.SanitizedCharField(max_length=100),
                default=list,
                size=None,
                verbose_name="keywords",
            ),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="notes",
            field=mcod.lib.model_sanitization.SanitizedTextField(null=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300, verbose_name="title"),
        ),
    ]
