# Generated by Django 2.2.9 on 2021-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_auto_20190604_2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
    ]
