# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0004_license_is_permanently_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="name",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="license",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=250, verbose_name="Title"),
        ),
    ]
