# Generated by Django 2.2.9 on 2020-06-09 12:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labevent",
            name="execution_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="labevent",
            name="notes",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Notes"),
        ),
    ]
