# Generated by Django 2.2.9 on 2020-06-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0003_auto_20200611_2353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labevent",
            name="execution_date",
            field=models.DateField(verbose_name="Execution date"),
        ),
    ]
