# Generated by Django 2.2.9 on 2020-06-30 08:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0006_history_20200629"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labevent",
            name="notes",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Notes"),
        ),
    ]
