# Generated by Django 2.2.9 on 2020-11-27 12:06

from django.db import migrations
import mcod.lib.widgets


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0007_auto_20200630_1018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labevent",
            name="notes",
            field=mcod.lib.widgets.RichTextUploadingField(verbose_name="Notes"),
        ),
    ]
