# Generated by Django 2.2.9 on 2021-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0008_auto_20201127_1306"),
    ]

    operations = [
        migrations.AddField(
            model_name="labevent",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="labreport",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
    ]
