# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0009_auto_20210423_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labevent",
            name="notes",
            field=mcod.lib.model_sanitization.SanitizedRichTextUploadingField(verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="labevent",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300, verbose_name="Title"),
        ),
    ]
