# Generated by Django 2.2 on 2019-08-26 08:03
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(os.path.join(settings.DATABASE_DIR, "MCOD-1608-newsletter-history_other.sql")).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "MCOD-1608-newsletter-history_other_backward.sql",
                )
            ).read(),
        )
    ]
