# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization
import mcod.newsletter.utils


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_auto_20190919_1349"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="message",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, verbose_name="message"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="activation_code",
            field=mcod.lib.model_sanitization.SanitizedCharField(
                default=mcod.newsletter.utils.make_activation_code, max_length=40, verbose_name="activation code"
            ),
        ),
    ]
