# Generated by Django 2.0.4 on 2018-08-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchhistories", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchhistory",
            old_name="q",
            new_name="query_sentence",
        ),
    ]
