# Generated by Django 2.0.4 on 2019-02-04 10:57
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("searchhistories", "0002_auto_20180817_1138"),
    ]

    operations = []
