# Generated by Django 2.0.4 on 2019-02-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchhistories", "0003_clear_searchhistories_with_empty_q"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchhistory",
            options={
                "verbose_name": "Search history",
                "verbose_name_plural": "Search Histories",
            },
        ),
    ]
