# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("searchhistories", "0004_auto_20190205_0902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchhistory",
            name="query_sentence",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=256),
        ),
    ]
