# Generated by Django 2.0.4 on 2018-05-25 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trash",
            fields=[],
            options={
                "verbose_name": "Trash",
                "verbose_name_plural": "Trash",
                "proxy": True,
                "indexes": [],
            },
            bases=("applications.application",),
        ),
        migrations.AlterModelOptions(
            name="application",
            options={
                "default_manager_name": "objects",
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
    ]
