# Generated by Django 2.0.4 on 2018-11-07 10:59

from django.db import migrations, models
import mcod.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_auto_20181031_1627"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="image_thumb",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=mcod.core.storages.ApplicationImagesStorage(base_url=None, location=None),
                upload_to="%Y%m%d",
            ),
        ),
    ]
