# Generated by Django 2.1.4 on 2019-02-27 10:08

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_application_image_thumb"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("slug", "title", "notes"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
