# Generated by Django 2.2 on 2019-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_auto_20190411_2047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="slug",
            field=models.SlugField(blank=True, max_length=600),
        ),
    ]
