# Generated by Django 2.2 on 2019-10-03 09:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("applications", "0012_auto_20190604_2022"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "under_title_cb",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.core.blocks.RichTextBlock(
                                    features=[
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "superscript",
                                        "subscript",
                                        "strikethroughdocument-link",
                                    ],
                                    label="Blok tekstu",
                                ),
                            ),
                            (
                                "image",
                                wagtail.images.blocks.ImageChooserBlock(label="Obrazek"),
                            ),
                        ],
                        blank=True,
                        default="",
                        help_text="Zawartość bloku, który znajdzie się pod tytułem strony głównej (nad wyszukiwarką).",
                        verbose_name="Blok pod tytułem",
                    ),
                ),
                (
                    "under_list_cb",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.core.blocks.RichTextBlock(
                                    features=[
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "superscript",
                                        "subscript",
                                        "strikethroughdocument-link",
                                    ],
                                    label="Blok tekstu",
                                ),
                            ),
                            (
                                "image",
                                wagtail.images.blocks.ImageChooserBlock(label="Obrazek"),
                            ),
                        ],
                        blank=True,
                        default="",
                        help_text="Zawartość bloku, który znajdzie się pod listą aplikacji.",
                        verbose_name="Blok pod listą aplikacji",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista aplikacji",
                "verbose_name_plural": "Listy aplikacji",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ApplicationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "intro",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="Krótki opis, streszczenie, zajawka.",
                        verbose_name="Intro",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "h1",
                                wagtail.core.blocks.CharBlock(classname="full title", icon="fa-header", label="H1"),
                            ),
                            (
                                "h2",
                                wagtail.core.blocks.CharBlock(classname="full title", icon="fa-header", label="H2"),
                            ),
                            (
                                "h3",
                                wagtail.core.blocks.CharBlock(classname="full title", icon="fa-header", label="H3"),
                            ),
                            (
                                "h4",
                                wagtail.core.blocks.CharBlock(classname="full title", icon="fa-header", label="H4"),
                            ),
                            (
                                "paragraph",
                                wagtail.core.blocks.RichTextBlock(
                                    features=[
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "superscript",
                                        "subscript",
                                        "strikethroughdocument-link",
                                    ],
                                    label="Blok tekstu",
                                ),
                            ),
                            (
                                "image",
                                wagtail.images.blocks.ImageChooserBlock(label="Obrazek"),
                            ),
                            (
                                "blockquote",
                                wagtail.core.blocks.BlockQuoteBlock(label="Cytat"),
                            ),
                            (
                                "document",
                                wagtail.documents.blocks.DocumentChooserBlock(label="Dokument"),
                            ),
                            ("media", wagtail.embeds.blocks.EmbedBlock(label="Media")),
                        ],
                        help_text="Właściwa treść strony.",
                        verbose_name="Treść",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Czy ten artykuł ma zostać wyróżniony?",
                        verbose_name="Wyróżnione",
                    ),
                ),
                (
                    "app_url_path",
                    models.TextField(blank=True, default="", verbose_name="Link URL do aplikacji"),
                ),
            ],
            options={
                "verbose_name": "Aplikacja",
                "verbose_name_plural": "Aplikacje",
            },
            bases=("wagtailcore.page",),
        ),
    ]
