# Generated by Django 2.2 on 2019-11-10 21:55

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_applicationindexpage_applicationpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="image_alt",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Alternative text"),
        ),
        migrations.AlterField(
            model_name="application",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("title", "notes", "image_alt", "slug"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
