# Generated by Django 2.2.9 on 2021-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0023_auto_20210415_1639"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="applicationproposal",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
    ]
