# Generated by Django 2.0.4 on 2018-04-26 09:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import mcod.core.storages
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        storage=mcod.core.storages.ResourcesStorage(base_url=None, location=None),
                        upload_to="",
                        verbose_name="File",
                    ),
                ),
                (
                    "format",
                    models.CharField(blank=True, max_length=150, null=True, verbose_name="Format"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("position", models.IntegerField(default=1, verbose_name="Position")),
                (
                    "customfields",
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="Customfields"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="title")),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Resource Link",
                    ),
                ),
                ("resource_type", models.TextField(verbose_name="Resource type")),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("downloads_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "db_table": "resource",
            },
        ),
    ]
