# Generated by Django 2.0.4 on 2018-05-07 12:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="resource",
            managers=[
                ("all_resources", django.db.models.manager.Manager()),
            ],
        ),
    ]
