# Generated by Django 2.0.4 on 2018-05-30 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0004_auto_20180525_1430"),
    ]

    operations = []
