# Generated by Django 2.0.4 on 2018-06-17 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_results", "0001_initial"),
        ("resources", "0005_auto_20180530_1250"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="customfields",
            new_name="old_customfields",
        ),
        migrations.RenameField(
            model_name="resource",
            old_name="format",
            new_name="old_format",
        ),
        migrations.RenameField(
            model_name="resource",
            old_name="link",
            new_name="old_link",
        ),
        migrations.RenameField(
            model_name="resource",
            old_name="file",
            new_name="old_file",
        ),
        migrations.RenameField(
            model_name="resource",
            old_name="resource_type",
            new_name="old_resource_type",
        ),
        migrations.AddField(
            model_name="resource",
            name="openness_score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Openness score",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="data_tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="data_task_resources",
                to="django_celery_results.TaskResult",
                verbose_name="Download Tasks",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="file_tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="file_task_resources",
                to="django_celery_results.TaskResult",
                verbose_name="Download Tasks",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="link_tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="link_task_resources",
                to="django_celery_results.TaskResult",
                verbose_name="Download Tasks",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="type",
            field=models.CharField(
                choices=[("file", "File"), ("website", "Web Site"), ("api", "API")],
                default="file",
                editable=False,
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="file_info",
            field=models.TextField(blank=True, editable=False, null=True, verbose_name="File info"),
        ),
        migrations.AddField(
            model_name="resource",
            name="file_encoding",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=150,
                null=True,
                verbose_name="File encoding",
            ),
        ),
    ]
