# Generated by Django 2.0.4 on 2018-11-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0008_additional_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="show_tabular_view",
            field=models.BooleanField(default=True, verbose_name="Tabular view"),
        ),
    ]
