# Generated by Django 2.1.4 on 2019-02-08 08:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_auto_20190205_0902"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="tabular_data_schema",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
