# Generated by Django 2.1.4 on 2019-02-25 09:57

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0012_resource_tabular_data_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("title", "description"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
