# Generated by Django 2.1.4 on 2019-03-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0013_resource_data_date"),
        ("resources", "0013_resource_i18n"),
    ]

    operations = []
