# Generated by Django 2.2 on 2019-05-06 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0017_auto_20190411_2047"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="verified",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Update date",
            ),
        ),
    ]
