# Generated by Django 2.2 on 2019-11-04 14:29
import os
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0022_chart"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(os.path.join(settings.DATABASE_DIR, "MCOD-1679-tg-resources-charts-history.sql")).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "MCOD-1679-tg-resources-charts-history_backward.sql",
                )
            ).read(),
        )
    ]
