# Generated by Django 2.2 on 2019-11-21 14:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0023_charts_history_trigger"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="chart",
            managers=[
                ("raw", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="chart",
            name="i18n",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="views_count",
        ),
    ]
