# Generated by Django 2.2.9 on 2020-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("special_signs", "0003_auto_20201218_1640"),
        ("resources", "0030_auto_20200910_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="special_signs",
            field=models.ManyToManyField(
                blank=True,
                related_name="special_signs_resources",
                to="special_signs.SpecialSign",
                verbose_name="special signs",
            ),
        ),
    ]
