# Generated by Django 2.2.9 on 2021-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0032_auto_20210129_1759"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="forced_api_type",
            field=models.BooleanField(default=False, verbose_name="Mark resource as API"),
        ),
    ]
