# Generated by Django 2.2.9 on 2021-04-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0034_resource_file_mimetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="is_chart_creation_blocked",
            field=models.BooleanField(default=False, verbose_name="is chart creation blocked?"),
        ),
    ]
