# Generated by Django 2.2.9 on 2021-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0035_resource_is_chart_creation_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="name"),
        ),
    ]
