# Generated by Django 2.2.9 on 2021-04-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0036_chart_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chart",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="chart",
            managers=[],
        ),
    ]
