# Generated by Django 2.2.9 on 2021-05-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0038_auto_20210425_1531"),
        ("resources", "0038_auto_20210426_1859"),
    ]

    operations = []
