# Generated by Django 2.2.9 on 2021-05-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0039_merge_20210507_1157"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="forced_file_type",
            field=models.BooleanField(default=False, verbose_name="Mark resource as file"),
        ),
    ]
