# Generated by Django 2.2.9 on 2021-05-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0041_auto_20210514_1137"),
        ("resources", "0040_resource_jsonld_file"),
    ]

    operations = []
