# Generated by Django 2.2.9 on 2021-12-16 14:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mcod.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0048_resource_regions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        storage=mcod.core.storages.ResourcesStorage(base_url=None, location=None),
                        upload_to="%Y%m%d",
                        verbose_name="File",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("abw", "ABW"),
                            ("bat", "BAT"),
                            ("bmp", "BMP"),
                            ("csv", "CSV"),
                            ("dbf", "DBF"),
                            ("doc", "DOC"),
                            ("docx", "DOCX"),
                            ("dot", "DOT"),
                            ("epub", "EPUB"),
                            ("geojson", "GEOJSON"),
                            ("geotiff", "GEOTIFF"),
                            ("gif", "GIF"),
                            ("gpx", "GPX"),
                            ("grib", "GRIB"),
                            ("grib2", "GRIB2"),
                            ("htm", "HTM"),
                            ("html", "HTML"),
                            ("jpe", "JPE"),
                            ("jpeg", "JPEG"),
                            ("jpg", "JPG"),
                            ("json", "JSON"),
                            ("json-ld", "JSON-LD"),
                            ("jsonld", "JSONLD"),
                            ("kml", "KML"),
                            ("md", "MD"),
                            ("n3", "N3"),
                            ("nc", "NC"),
                            ("nquads", "NQUADS"),
                            ("nt", "NT"),
                            ("nt11", "NT11"),
                            ("ntriples", "NTRIPLES"),
                            ("odc", "ODC"),
                            ("odf", "ODF"),
                            ("odg", "ODG"),
                            ("odi", "ODI"),
                            ("odp", "ODP"),
                            ("ods", "ODS"),
                            ("odt", "ODT"),
                            ("pdf", "PDF"),
                            ("png", "PNG"),
                            ("pot", "POT"),
                            ("ppa", "PPA"),
                            ("ppm", "PPM"),
                            ("pps", "PPS"),
                            ("ppt", "PPT"),
                            ("pptx", "PPTX"),
                            ("ps", "PS"),
                            ("pwz", "PWZ"),
                            ("rd", "RD"),
                            ("rdf", "RDF"),
                            ("rtf", "RTF"),
                            ("shp", "SHP"),
                            ("svg", "SVG"),
                            ("tex", "TEX"),
                            ("texi", "TEXI"),
                            ("texinfo", "TEXINFO"),
                            ("tif", "TIF"),
                            ("tiff", "TIFF"),
                            ("trig", "TRIG"),
                            ("trix", "TRIX"),
                            ("tsv", "TSV"),
                            ("ttl", "TTL"),
                            ("turtle", "TURTLE"),
                            ("txt", "TXT"),
                            ("vsd", "VSD"),
                            ("webp", "WEBP"),
                            ("wiz", "WIZ"),
                            ("wsdl", "WSDL"),
                            ("xbm", "XBM"),
                            ("xlb", "XLB"),
                            ("xls", "XLS"),
                            ("xlsx", "XLSX"),
                            ("xml", "XML"),
                            ("xpdl", "XPDL"),
                            ("xsl", "XSL"),
                        ],
                        max_length=150,
                        null=True,
                        verbose_name="Format",
                    ),
                ),
                (
                    "mimetype",
                    models.TextField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="File mimetype",
                    ),
                ),
                (
                    "info",
                    models.TextField(blank=True, editable=False, null=True, verbose_name="File info"),
                ),
                (
                    "encoding",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=150,
                        null=True,
                        verbose_name="File encoding",
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "openness_score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Openness score",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="resources.Resource",
                    ),
                ),
            ],
        ),
    ]
