# Generated by Django 2.2.9 on 2022-03-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0053_auto_20220307_0856"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="has_research_data",
            field=models.NullBooleanField(verbose_name="has research data"),
        ),
    ]
