# Generated by Django 2.2.9 on 2022-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0061_auto_20220712_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="language",
            field=models.CharField(
                choices=[("pl", "polish"), ("en", "english")],
                db_index=True,
                default="pl",
                max_length=2,
                verbose_name="language version of the data",
            ),
        ),
    ]
