# Generated by Django 2.2.9 on 2023-12-19 08:56

from django.db import migrations, models
import mcod.core.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0065_auto_20220812_1656"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[mcod.core.model_validators.illegal_character_validator],
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(
                max_length=500,
                validators=[mcod.core.model_validators.illegal_character_validator],
                verbose_name="title",
            ),
        ),
    ]
