# Generated by Django 2.2.9 on 2024-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0066_auto_20231219_0956"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="contains_protected_data",
            field=models.BooleanField(default=False, verbose_name="Contains protected data list"),
        ),
    ]
