# Generated by Django 2.2.9 on 2024-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0068_aggregateddgainfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="has_high_value_data_from_ec_list",
            field=models.NullBooleanField(verbose_name="has high value data from the EC list"),
        ),
    ]
