# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization
import mcod.core.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0069_resource_has_high_value_data_from_ec_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=mcod.lib.model_sanitization.SanitizedTextField(
                blank=True,
                null=True,
                validators=[mcod.core.model_validators.illegal_character_validator],
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="i18n",
            field=mcod.lib.model_sanitization.SanitizedTranslationField(
                fields=("title", "description", "slug"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(
                max_length=500, validators=[mcod.core.model_validators.illegal_character_validator], verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="supplement",
            name="i18n",
            field=mcod.lib.model_sanitization.SanitizedTranslationField(
                fields=("name", "slug"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="supplement",
            name="language",
            field=mcod.lib.model_sanitization.SanitizedCharField(
                choices=[("pl", "Polish"), ("en", "English")], default="pl", max_length=2, verbose_name="language"
            ),
        ),
        migrations.AlterField(
            model_name="supplement",
            name="name",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=200, verbose_name="name"),
        ),
    ]
