# Generated by Django 2.2.9 on 2025-09-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0072_auto_20250418_1050"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskresult",
            options={"get_latest_by": "date_done"},
        ),
    ]
