# Generated by Django 2.2 on 2019-04-10 12:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("object_restored", "Object republished"),
                            ("object_removed", "Object withdrawaled"),
                            ("object_updated", "Object updated"),
                            ("related_object_publicated", "Related object publicated"),
                            ("related_object_updated", "Related object updated"),
                            ("related_object_restored", "Related object republished"),
                            ("related_object_removed", "Related object withdrawaled"),
                            ("result_count_incresed", "Results incresed"),
                            ("result_count_decresed", "Results decresed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(choices=[("new", "New"), ("read", "Read")], max_length=20),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("include_in_report", models.BooleanField(default=True)),
                (
                    "customfields",
                    django.contrib.postgres.fields.jsonb.JSONField(null=True),
                ),
                ("reported_till", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Watcher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "watcher_type",
                    models.CharField(
                        choices=[("model", "Model"), ("search_query", "Search query")],
                        default="model",
                        max_length=15,
                    ),
                ),
                ("object_name", models.CharField(max_length=128)),
                ("object_ident", models.CharField(max_length=256)),
                ("ref_field", models.CharField(default="last_modified", max_length=64)),
                ("ref_value", models.TextField()),
                ("last_ref_change", models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="watcher",
            index=models.Index(
                fields=["watcher_type", "object_name", "object_ident"],
                name="watchers_wa_watcher_cac58f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="watcher",
            constraint=models.UniqueConstraint(
                fields=("watcher_type", "object_name", "object_ident"),
                name="unique_model_watcher",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="watcher",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="watchers.Watcher",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="subscription",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="watchers.Subscription",
            ),
        ),
        migrations.CreateModel(
            name="ModelWatcher",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("watchers.watcher",),
        ),
        migrations.CreateModel(
            name="SearchQueryWatcher",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("watchers.watcher",),
        ),
    ]
