# Generated by Django 2.2 on 2019-05-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="include_in_report",
            new_name="enable_notifications",
        ),
    ]
