# Generated by Django 2.2 on 2019-06-15 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("watchers", "0002_auto_20190507_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watcher",
            name="watcher_type",
            field=models.CharField(
                choices=[("model", "Model"), ("query", "Search query")],
                default="model",
                max_length=15,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "watcher")},
        ),
    ]
