# Generated by Django 2.2 on 2019-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0003_auto_20190615_0736"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
