# Generated by Django 2.2 on 2019-06-18 07:38
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watchers", "0004_watcher_is_active"),
    ]

    operations = [
        migrations.RunSQL(open(os.path.join(settings.DATABASE_DIR, "MCOD-1242-watchers_history_other.sql")).read()),
    ]
