# Generated by Django 2.2 on 2019-06-25 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("watchers", "0006_auto_20190625_2049"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "watcher"), ("user", "name")},
        ),
    ]
