# Generated by Django 2.2 on 2019-07-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0009_watcher_api_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watcher",
            name="api_version",
        ),
    ]
