# Generated by Django 2.2 on 2019-07-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0010_remove_watcher_api_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="ref_value",
            field=models.TextField(null=True),
        ),
    ]
