# Generated by Django 2.2 on 2019-07-04 07:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0011_notification_ref_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="customfields",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
