# Generated by Django 2.2 on 2019-07-04 07:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0012_watcher_customfields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watcher",
            name="customfields",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
