# Generated by Django 2.2 on 2019-09-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0013_auto_20190704_0959"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="enable_notifications",
        ),
    ]
