# Generated by Django 2.2.9 on 2020-06-29 07:19

from django.db import migrations


def normalize_search_urls(apps, schema_editor):
    model = apps.get_model("watchers", "SearchQueryWatcher")
    from mcod.watchers.models import SearchQueryWatcherManager

    for x in model.objects.all():
        x.object_ident = SearchQueryWatcherManager._normalize_url(x.object_ident)
        x.save()


def reverse_normalize_search_urls(apps, schema_editor):
    # there is no way back...
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0015_search_subscriptions"),
    ]

    operations = [
        migrations.RunPython(normalize_search_urls, reverse_normalize_search_urls),
    ]
