# Generated by Django 2.0 on 2018-03-26 10:06
# flake8: noqa

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
