# Generated by Django 2.0 on 2018-04-03 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_history"),
    ]

    operations = [
        migrations.RunSQL(
            """
BEGIN;

/* 1. NOWY SCHEMAT INTERNALS */
CREATE SCHEMA IF NOT EXISTS internals;


/* 2. TABELA FUNCTIONS_EXECUTE_LOG */
/* usun tabele */
DROP TABLE IF EXISTS internals.functions_execute_log;

/* stworz tabele */
CREATE TABLE internals.functions_execute_log
(
  id                   BIGSERIAL                   NOT NULL,
  function_schema      VARCHAR(255)                NOT NULL,
  function_name        VARCHAR(255)                NOT NULL,
  start_timestamp      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_timestamp        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  diff_timestamp       INTERVAL                    NOT NULL,
  incoming_parameters  VARCHAR(500)                NULL,
  returned_sqlstate    TEXT                        NULL,
  message_text         TEXT                        NULL,
  pg_exception_detail  TEXT                        NULL,
  table_name           TEXT                        NULL,
  schema_name          TEXT                        NULL,
  column_name          TEXT                        NULL,
  constraint_name      TEXT                        NULL,
  pg_datatype_name     TEXT                        NULL,
  pg_exception_hint    TEXT                        NULL,
  pg_exception_context TEXT                        NULL
);

/* stworz PK */
ALTER TABLE internals.functions_execute_log
  ADD CONSTRAINT PK_functions_execute_log_id PRIMARY KEY (id);


/*
SELECT *
FROM internals.functions_execute_log;
*/
COMMIT;

        """
        )
    ]
