# Generated by Django 2.0.4 on 2018-08-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20180625_1109"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfollowinguser",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="userfollowinguser",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="followed_users",
        ),
        migrations.DeleteModel(
            name="UserFollowingUser",
        ),
    ]
