# Generated by Django 2.0.4 on 2019-01-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20190114_1324"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="customfields",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_internal",
            field=models.CharField(
                blank=True,
                db_column="tel_internal",
                max_length=20,
                null=True,
                verbose_name="int.",
            ),
        ),
    ]
