# Generated by Django 2.2 on 2019-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20190911_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lang",
            field=models.CharField(
                choices=[("pl", "Polish"), ("en", "English")],
                default="pl",
                max_length=2,
                verbose_name="User language",
            ),
        ),
    ]
