# Generated by Django 2.2.9 on 2020-05-19 12:31

from django.db import migrations, models


def set_gov_user_types(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email__endswith="gov.pl").update(is_official=True)


def reverse_gov_user_types(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_official",
            field=models.BooleanField(default=False, verbose_name="Official"),
        ),
        migrations.RunPython(set_gov_user_types, reverse_gov_user_types),
    ]
