# Generated by Django 2.2.9 on 2020-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_is_official"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_representative",
            field=models.BooleanField(default=False, verbose_name="representative"),
        ),
    ]
