# Generated by Django 2.2.9 on 2020-09-07 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mcod.core.db.mixins
import mcod.core.storages
import model_utils.fields
import modeltrans.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_is_representative"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, max_length=600)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "removed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        when={True},
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=300, verbose_name="title")),
                ("venue", models.CharField(max_length=300, verbose_name="venue")),
                ("description", models.TextField(verbose_name="agenda")),
                (
                    "start_date",
                    models.DateField(null=True, verbose_name="meeting date"),
                ),
                ("start_time", models.TimeField(null=True, verbose_name="start time")),
                ("end_time", models.TimeField(null=True, verbose_name="end time")),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(fields=("slug",), required_languages=(), virtual_fields=True),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="members",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting",
                "verbose_name_plural": "meetings",
                "default_manager_name": "objects",
            },
            bases=(
                mcod.core.db.mixins.AdminMixin,
                mcod.core.db.mixins.ApiMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MeetingFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, max_length=600)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "removed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        when={True},
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "file",
                    models.FileField(
                        max_length=2000,
                        storage=mcod.core.storages.MeetingStorage(base_url=None, location=None),
                        upload_to="",
                        verbose_name="file",
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(fields=("slug",), required_languages=(), virtual_fields=True),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="files",
                        to="users.Meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting file",
                "verbose_name_plural": "meeting files",
                "default_manager_name": "objects",
            },
            bases=(
                mcod.core.db.mixins.AdminMixin,
                mcod.core.db.mixins.ApiMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MeetingTrash",
            fields=[],
            options={
                "verbose_name": "Trash (Meeting)",
                "verbose_name_plural": "Trash (Meetings)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.meeting",),
        ),
    ]
