# Generated by Django 2.2.9 on 2020-09-07 13:41
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_meeting_meetingfile_meetingtrash"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(os.path.join(settings.DATABASE_DIR, "ODSOFT-618-users-meeting-history_other.sql")).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-618-users-meeting-history_other_backward.sql",
                )
            ).read(),
        )
    ]
