# Generated by Django 2.2.9 on 2020-10-22 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mcod.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_auto_20200417_0907"),
        ("users", "0016_meeting_history_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent_organization_main",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_organization_main_users",
                to="organizations.Organization",
                verbose_name="main organization of agent",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="agent_organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="agents",
                to="organizations.Organization",
                verbose_name="Organizations",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="extra_agent_of",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=mcod.users.models.agents_choices,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_agent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="extra agent of",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(default=False, verbose_name="agent"),
        ),
    ]
