# Generated by Django 2.2.9 on 2020-10-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_migrate_is_representative_to_is_agent_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_representative",
        ),
    ]
