# Generated by Django 2.2.9 on 2021-10-13 07:44

from django.db import migrations, models
import mcod.core.storages
import mcod.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_auto_20210531_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingfile",
            name="file",
            field=models.FileField(
                max_length=2000,
                storage=mcod.core.storages.MeetingStorage(base_url=None, location=None),
                upload_to=mcod.users.models.meeting_file_path,
                verbose_name="file",
            ),
        ),
    ]
