# Generated by Django 2.2.9 on 2022-06-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_auto_20220602_1524"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followed_applications",
        ),
        migrations.DeleteModel(
            name="UserFollowingApplication",
        ),
    ]
