# Generated by Django 2.2.9 on 2024-05-22 09:50

from django.conf import settings
from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_auto_20220609_0920"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="_pesel",
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pesel",
            field=encrypted_fields.fields.SearchField(
                blank=True,
                db_index=True,
                encrypted_field_name="_pesel",
                hash_key=settings.FIELD_ENCRYPTION_KEYS[0],
                max_length=66,
                null=True,
            ),
        ),
    ]
