# Generated by Django 2.2.9 on 2024-07-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_auto_20240522_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_gov_auth",
            field=models.BooleanField(default=False),
        ),
    ]
