# Generated by Django 2.2.9 on 2024-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_user_is_gov_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_logged_method",
            field=models.CharField(blank=True, choices=[("WK", "WK"), ("Formularz", "Formularz")], max_length=50, null=True),
        ),
    ]
