# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_user_last_logged_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=mcod.lib.model_sanitization.SanitizedTextField(verbose_name="agenda"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="venue",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300, verbose_name="venue"),
        ),
        migrations.AlterField(
            model_name="user",
            name="fullname",
            field=mcod.lib.model_sanitization.SanitizedCharField(blank=True, max_length=100, null=True, verbose_name="Full name"),
        ),
    ]
