# Generated by Django 2.2.9 on 2025-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20241029_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_logged_method',
            field=models.CharField(blank=True, choices=[('WK', 'WK'), ('Form', 'Form')], max_length=50, null=True),
        ),
    ]
