# Generated by Django 2.1.4 on 2019-02-25 10:02

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="i18n",
            field=modeltrans.fields.TranslationField(fields=("name",), required_languages=("pl",), virtual_fields=True),
        ),
    ]
