# Generated by Django 2.2.9 on 2021-02-08 17:05

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0009_create_keywords_from_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="i18n",
            field=modeltrans.fields.TranslationField(fields=("name", "slug"), required_languages=("pl",), virtual_fields=True),
        ),
    ]
