# Generated by Django 2.2.9 on 2021-06-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0012_remove_tags_without_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="language",
            field=models.CharField(
                choices=[("pl", "Polish"), ("en", "English")],
                db_index=True,
                default="pl",
                max_length=2,
                verbose_name="language",
            ),
        ),
    ]
