# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0013_auto_20210615_0122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=100, verbose_name="name"),
        ),
    ]
