# Generated by Django 2.2.9 on 2021-10-28 14:20

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mcod.core.db.mixins
import model_utils.fields
import modeltrans.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0047_auto_20211012_1443"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=600)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=150, verbose_name="title")),
                ("region_id", models.PositiveIntegerField()),
                (
                    "region_type",
                    models.CharField(
                        choices=[
                            ("locality", "locality"),
                            ("localadmin", "localadmin"),
                            ("county", "county"),
                            ("region", "region"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "bbox",
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="Boundary box"),
                ),
                (
                    "lat",
                    models.DecimalField(decimal_places=8, max_digits=10, verbose_name="Latitude"),
                ),
                (
                    "lng",
                    models.DecimalField(decimal_places=8, max_digits=10, verbose_name="Longitude"),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=("name", "slug"),
                        required_languages=(),
                        virtual_fields=True,
                    ),
                ),
            ],
            bases=(
                mcod.core.db.mixins.AdminMixin,
                mcod.core.db.mixins.ApiMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ResourceRegion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_additional", models.BooleanField(default=False)),
                (
                    "region",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="regions.Region"),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.Resource",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="region",
            index=django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="regions_reg_i18n_832f5a_gin"),
        ),
        migrations.AlterUniqueTogether(
            name="resourceregion",
            unique_together={("region", "resource")},
        ),
    ]
