# Generated by Django 2.2.9 on 2021-11-04 12:50
from decimal import Decimal
from django.db import migrations
from django.conf import settings


def create_default_region(apps, schema_editor):
    region = apps.get_model("regions", "Region")
    region.objects.create(
        region_id=settings.DEFAULT_REGION_ID,
        name="Polska",
        i18n={"name_en": "Poland"},
        region_type="country",
        bbox=["14.122885", "49.002047", "24.145783", "54.836417"],
        lat=Decimal("51.99605"),
        lng=Decimal("19.488789"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0002_auto_20211104_1350"),
    ]

    operations = [
        migrations.RunPython(create_default_region, reverse_code=migrations.RunPython.noop),
    ]
