# Generated by Django 2.2.9 on 2021-11-08 13:13

from django.db import migrations
from django.conf import settings


def update_default_region(apps, schema_editor):
    region = apps.get_model("regions", "Region")
    default_reg = region.objects.get(region_id=settings.DEFAULT_REGION_ID)
    default_reg.geonames_id = 798544
    default_reg.save()


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0004_region_geonames_id"),
    ]

    operations = [
        migrations.RunPython(update_default_region, reverse_code=migrations.RunPython.noop),
    ]
