# Generated by Django 2.2.9 on 2022-07-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0007_auto_20211119_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="region_id",
            field=models.CharField(max_length=10),
        ),
    ]
