# Generated by Django 2.1.4 on 2019-02-15 08:15
import os
from django.conf import settings

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0002_auto_20190205_0902"),
        ("resources", "0012_resource_tabular_data_schema"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "MCOD-1308-mv-resource-dataset-organization-report.sql",
                )
            ).read(),
            reverse_sql=open(os.path.join(settings.DATABASE_DIR, "MCOD-1308-back.sql")).read(),
        )
    ]
