# Generated by Django 2.1.4 on 2019-02-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_create_m_view_for_raports"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryDailyReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "file",
                    models.CharField(max_length=512, null=True, verbose_name="File path"),
                ),
                ("status", models.CharField(default="SUCCESS", max_length=20)),
                (
                    "ordered_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_ordered_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ordered by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Summary daily report",
                "verbose_name_plural": "Summary daily reports",
            },
        ),
    ]
