# Generated by Django 2.2.9 on 2020-07-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_summarydailyreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationProposalReport",
            fields=[],
            options={
                "verbose_name": "Application proposal report",
                "verbose_name_plural": "Application proposal reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.report",),
        ),
    ]
