# Generated by Django 2.2.9 on 2020-08-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_applicationproposalreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApplicationProposalReport",
        ),
        migrations.CreateModel(
            name="MonitoringReport",
            fields=[],
            options={
                "verbose_name": "Monitoring report",
                "verbose_name_plural": "Monitoring reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.report",),
        ),
    ]
