# Generated by Django 2.2.9 on 2021-12-13 13:52
import os

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_new_counters_in_daily_reports"),
        ("resources", "0049_resourcefile"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2504-separate-resource-files-table.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2504-separate-resource-files-table-backward.sql",
                )
            ).read(),
        ),
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2504-separate-resource-files-table-new-counters.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2504-separate-resource-files-table-new-counters-backward.sql",
                )
            ).read(),
        ),
    ]
