# Generated by Django 2.2.9 on 2022-04-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_separate_files_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.report",),
        ),
    ]
