# Generated by Django 2.2.9 on 2022-06-01 14:50
import os
from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0012_dashboard"),
        ("resources", "0054_resource_has_research_data"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(os.path.join(settings.DATABASE_DIR, "ODSOFT-3173-dynamic-and-high-value-data.sql")).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-3173-dynamic-and-high-value-data-backward.sql",
                )
            ).read(),
        ),
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-3173-dynamic-high-value-and-research-data.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-3173-dynamic-high-value-and-research-data-backward.sql",
                )
            ).read(),
        ),
    ]
