# Generated by Django 2.2.9 on 2025-02-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_ec_list_in_daily_reports"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceImportReport",
            fields=[],
            options={
                "verbose_name": "Data source",
                "verbose_name_plural": "Data source reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.report",),
        ),
        migrations.AlterModelOptions(
            name="resourcereport",
            options={"verbose_name": "Resource report", "verbose_name_plural": "Resource reports"},
        ),
    ]
