# Generated by Django 2.2.9 on 2020-12-15 14:43

from django.db import migrations, models
import django.utils.timezone
import mcod.core.db.mixins
import model_utils.fields
import modeltrans.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecialSign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, max_length=600)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "removed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="is_removed",
                        when={True},
                    ),
                ),
                (
                    "published_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        when={"published"},
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("symbol", models.CharField(max_length=30, verbose_name="symbol")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=("name", "description", "slug"),
                        required_languages=("pl",),
                        virtual_fields=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "special sign",
                "verbose_name_plural": "special signs",
                "default_manager_name": "objects",
            },
            bases=(
                mcod.core.db.mixins.AdminMixin,
                mcod.core.db.mixins.ApiMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SpecialSignTrash",
            fields=[],
            options={
                "verbose_name": "Trash (Special Signs)",
                "verbose_name_plural": "Trash (Special Signs)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("special_signs.specialsign",),
        ),
    ]
