# Generated by Django 2.2.9 on 2020-12-15 14:30
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("special_signs", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-1176-special_signs-specialsign-history_other.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-1176-special_signs-specialsign-history_other_backward.sql",
                )
            ).read(),
        )
    ]
