# Generated by Django 2.2.9 on 2021-04-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("special_signs", "0003_auto_20201218_1640"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpecialSignTrash",
        ),
    ]
