# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("special_signs", "0005_specialsign_is_permanently_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialsign",
            name="description",
            field=mcod.lib.model_sanitization.SanitizedTextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="specialsign",
            name="name",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=100, verbose_name="name"),
        ),
    ]
