# Generated by Django 2.2.9 on 2020-12-10 12:35
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_guide_history_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-1006-guides-guideitem-history_other.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-1006-guides-guideitem-history_other_backward.sql",
                )
            ).read(),
        )
    ]
