# Generated by Django 2.2.9 on 2021-01-27 16:38

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0005_auto_20210113_1238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="i18n",
            field=modeltrans.fields.TranslationField(fields=("title", "slug"), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name="guideitem",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("title", "content", "slug"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
