# Generated by Django 2.2.9 on 2021-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0006_auto_20210127_1738"),
    ]

    operations = [
        migrations.AddField(
            model_name="guideitem",
            name="is_expandable",
            field=models.BooleanField(default=False, verbose_name="element is expandable"),
        ),
    ]
