# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0008_auto_20210423_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="i18n",
            field=mcod.lib.model_sanitization.SanitizedTranslationField(
                fields=("title", "slug"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="guideitem",
            name="content",
            field=mcod.lib.model_sanitization.SanitizedTextField(verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="guideitem",
            name="css_selector",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300, verbose_name="css selector"),
        ),
        migrations.AlterField(
            model_name="guideitem",
            name="i18n",
            field=mcod.lib.model_sanitization.SanitizedTranslationField(
                fields=("title", "content", "slug"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="guideitem",
            name="route",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=200, verbose_name="route"),
        ),
        migrations.AlterField(
            model_name="guideitem",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=200, verbose_name="title"),
        ),
    ]
