# Generated by Django 2.2.9 on 2025-12-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'Elektronika'), ('clothing', 'Ubrania'), ('wallets/money', 'portfel/pieniadze'), ('jewellery', 'Bizuteria'), ('documents', 'Dokumenty'), ('animal', 'Zwierzeta'), ('other', 'Inne')], default=None, max_length=20)),
                ('name', models.CharField(help_text='Np. Pęk kluczy z breloczkiem misia', max_length=255, verbose_name='Nazwa przedmiotu')),
                ('description', models.TextField(blank=True, verbose_name='Opis szczegółowy')),
                ('date_found', models.DateField()),
                ('location_city', models.CharField(max_length=100, verbose_name='Miejscowość')),
                ('location_description', models.TextField(blank=True, help_text='Np. Park Miejski, ławka przy stawie, autobus linii 105', verbose_name='Miejsce znalezienia')),
                ('is_claimed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('lost', 'Zgubiony'), ('found', 'Znaleziony'), ('claimed', 'Odebrany')], default=None, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_and_found/%Y/%m/', verbose_name='Zdjęcie przedmiotu')),
                ('contact_info', models.TextField(help_text='Gdzie odebrać? Telefon, pokój w urzędzie itp.', verbose_name='Informacje kontaktowe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rzecz znaleziona',
                'verbose_name_plural': 'Rzeczy znalezione',
            },
        ),
    ]
