# Generated by Django 2.2 on 2019-10-09 09:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
    ]

    operations = [
        migrations.CreateModel(
            name="RootPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "over_search_field_cb",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "banner",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="\n                                Obraz będzie przycięty do rozmiarów TODO.\n                                ",
                                                label="Obraz",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "action_url",
                                            wagtail.core.blocks.URLBlock(required=True),
                                        ),
                                        (
                                            "target",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("_self", "To samo okno"),
                                                    ("_blank", "Nowe okno"),
                                                ]
                                            ),
                                        ),
                                    ],
                                    label="Baner reklamowy",
                                ),
                            ),
                            (
                                "video",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "video",
                                            wagtail.embeds.blocks.EmbedBlock(
                                                help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                                label="Wideo",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="\n                                    Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków \n                                ",
                                                label="Podpis",
                                                max_length=60,
                                                required=False,
                                                rows=2,
                                            ),
                                        ),
                                    ],
                                    label="Film",
                                ),
                            ),
                        ],
                        blank=True,
                        default="",
                    ),
                ),
                (
                    "over_latest_news_cb",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "banner",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="\n                                Obraz będzie przycięty do rozmiarów TODO.\n                                ",
                                                label="Obraz",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "action_url",
                                            wagtail.core.blocks.URLBlock(required=True),
                                        ),
                                        (
                                            "target",
                                            wagtail.core.blocks.ChoiceBlock(
                                                choices=[
                                                    ("_self", "To samo okno"),
                                                    ("_blank", "Nowe okno"),
                                                ]
                                            ),
                                        ),
                                    ],
                                    label="Baner reklamowy",
                                ),
                            ),
                            (
                                "video",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "video",
                                            wagtail.embeds.blocks.EmbedBlock(
                                                help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                                label="Wideo",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.TextBlock(
                                                help_text="\n                                    Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków \n                                ",
                                                label="Podpis",
                                                max_length=60,
                                                required=False,
                                                rows=2,
                                            ),
                                        ),
                                    ],
                                    label="Film",
                                ),
                            ),
                        ],
                        blank=True,
                        default="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strona główna",
                "verbose_name_plural": "Strony główne",
            },
            bases=("wagtailcore.page",),
        ),
    ]
