# Generated by Django 2.2 on 2019-10-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("cms", "0002_auto_20191009_1323"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rootpage",
            name="custom_background",
        ),
        migrations.AddField(
            model_name="rootpage",
            name="background_color",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="rootpage",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="rootpage",
            name="background_paralax",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
