# Generated by Django 2.2.9 on 2020-05-13 16:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_auto_20200227_0943"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formfielden",
            name="page",
        ),
        migrations.AddField(
            model_name="formpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    ("text", wagtail.core.blocks.RichTextBlock(label="Blok tekstu")),
                    (
                        "fieldset",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "legend",
                                    wagtail.core.blocks.RichTextBlock(label="Pytanie/wstęp", required=False),
                                ),
                                (
                                    "required",
                                    wagtail.core.blocks.BooleanBlock(
                                        default=False,
                                        label="Czy odpowiedź jest konieczna?",
                                        required=False,
                                    ),
                                ),
                                (
                                    "fields",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "label",
                                                    wagtail.core.blocks.CharBlock(
                                                        help_text="Etykieta pola",
                                                        label="Etykieta",
                                                        max_length=200,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "field_type",
                                                    wagtail.core.blocks.ChoiceBlock(
                                                        choices=[
                                                            (
                                                                "singleline",
                                                                "Single line text",
                                                            ),
                                                            (
                                                                "multiline",
                                                                "Multi-line text",
                                                            ),
                                                            ("email", "Email"),
                                                            ("number", "Number"),
                                                            ("url", "URL"),
                                                            ("checkbox", "Checkbox"),
                                                            (
                                                                "checkbox_with_field",
                                                                "Checkbox z polem",
                                                            ),
                                                            ("dropdown", "Drop down"),
                                                            ("radio", "Radio button"),
                                                            (
                                                                "radio_with_field",
                                                                "Radio button z polem",
                                                            ),
                                                            ("hidden", "Hidden field"),
                                                        ],
                                                        classname="formbuilder-type",
                                                        label="Rodzaj pola",
                                                        max_length=16,
                                                    ),
                                                ),
                                                (
                                                    "help_text",
                                                    wagtail.core.blocks.RichTextBlock(
                                                        label="Wskazówki, dodatkowe informacje.",
                                                        required=False,
                                                    ),
                                                ),
                                            ],
                                            label="Pole formularza",
                                        ),
                                        icon="form",
                                        label="Pola formularza",
                                    ),
                                ),
                            ],
                            icon="form",
                            label="Formularz",
                        ),
                    ),
                ],
                blank=True,
                help_text="Wybierz blok",
                null=True,
                verbose_name="Zawartość strony",
            ),
        ),
        migrations.AlterField(
            model_name="formpage",
            name="thank_you_text",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text="Komunikat, który zostanie wyświetlony po zakończeniu ankiety.",
                verbose_name="Tekst po zakończeniu",
            ),
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
        migrations.DeleteModel(
            name="FormFieldEn",
        ),
    ]
