# Generated by Django 2.2.9 on 2020-05-19 12:24

from django.db import migrations
import hypereditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0012_auto_20200519_0814"),
    ]

    operations = [
        migrations.AddField(
            model_name="kbcategorypage",
            name="body",
            field=hypereditor.fields.HyperField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="kbcategorypage",
            name="body_en",
            field=hypereditor.fields.HyperField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="kbrootpage",
            name="body",
            field=hypereditor.fields.HyperField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="kbrootpage",
            name="body_en",
            field=hypereditor.fields.HyperField(blank=True, default=None, null=True),
        ),
    ]
