# Generated by Django 2.2.9 on 2020-05-20 05:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0013_auto_20200519_1424"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpage",
            name="body",
        ),
        migrations.CreateModel(
            name="FormsetEn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(help_text="Tytuł", max_length=255, verbose_name="Tytuł"),
                ),
                (
                    "description",
                    wagtail.core.fields.RichTextField(blank=True, null=True),
                ),
                ("required", models.BooleanField(blank=True, default=False)),
                ("ident", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "fields",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "radiobutton",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "value",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Wartość pola.",
                                                label="Wartość",
                                                max_length=100,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "checked",
                                            wagtail.core.blocks.BooleanBlock(
                                                help_text="",
                                                label="Zaznaczony domyslnie.",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    label="Radio Button",
                                ),
                            )
                        ]
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formsets_en",
                        to="cms.FormPage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Formset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(help_text="Tytuł", max_length=255, verbose_name="Tytuł"),
                ),
                (
                    "description",
                    wagtail.core.fields.RichTextField(blank=True, null=True),
                ),
                ("required", models.BooleanField(blank=True, default=False)),
                ("ident", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "fields",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "radiobutton",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "value",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Wartość pola.",
                                                label="Wartość",
                                                max_length=100,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "checked",
                                            wagtail.core.blocks.BooleanBlock(
                                                help_text="",
                                                label="Zaznaczony domyslnie.",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    label="Radio Button",
                                ),
                            )
                        ]
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formsets",
                        to="cms.FormPage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
