# Generated by Django 2.2.9 on 2020-05-20 06:02

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0014_auto_20200520_0725"),
    ]

    operations = [
        migrations.AddField(
            model_name="formset",
            name="default_value",
            field=models.CharField(
                blank=True,
                help_text="Default value. Comma separated values supported for checkboxes.",
                max_length=255,
                verbose_name="default value",
            ),
        ),
        migrations.AddField(
            model_name="formset",
            name="help_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="help text"),
        ),
        migrations.AddField(
            model_name="formseten",
            name="default_value",
            field=models.CharField(
                blank=True,
                help_text="Default value. Comma separated values supported for checkboxes.",
                max_length=255,
                verbose_name="default value",
            ),
        ),
        migrations.AddField(
            model_name="formseten",
            name="help_text",
            field=models.CharField(blank=True, max_length=255, verbose_name="help text"),
        ),
        migrations.AlterField(
            model_name="formset",
            name="fields",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "radiobutton",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta pola.",
                                        label="Etykieta",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=100,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio Button",
                        ),
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="formseten",
            name="fields",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "radiobutton",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta pola.",
                                        label="Etykieta",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=100,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio Button",
                        ),
                    )
                ]
            ),
        ),
    ]
