# Generated by Django 2.2.9 on 2020-08-19 10:38

from django.db import migrations, models
import django.db.models.deletion
import mcod.core.db.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("cms", "0018_auto_20200717_1012"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraSimplePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="The page title as you'd like it to be seen by the public",
                        max_length=255,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True,
                        help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.",
                        max_length=255,
                        null=True,
                        verbose_name="page title",
                    ),
                ),
                (
                    "search_description_en",
                    models.TextField(blank=True, null=True, verbose_name="search description"),
                ),
                (
                    "draft_title_en",
                    models.CharField(editable=False, max_length=255, null=True),
                ),
                ("body", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Deklaracja dostępności",
                "verbose_name_plural": "Deklaracje dostępności",
                "abstract": False,
            },
            bases=(mcod.core.db.mixins.ApiMixin, "wagtailcore.page"),
        ),
    ]
