# Generated by Django 2.2.9 on 2020-09-29 07:46

from django.db import migrations
import mcod.cms.blocks.common
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0019_auto_20200819_1238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formset",
            name="fields",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "radiobutton",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button",
                        ),
                    ),
                    (
                        "radiobuttonwithinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku radio.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button z polem tekstowym",
                        ),
                    ),
                    (
                        "radiobuttonwithmultilineinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku radio.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button z polem wielolinijkowym tekstowym",
                        ),
                    ),
                    (
                        "checkbox",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox",
                        ),
                    ),
                    (
                        "checkboxwithinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku checkbox.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox z polem tekstowym",
                        ),
                    ),
                    (
                        "checkboxwithmultilineinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku checkbox.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox z wieloninijkowym polem tekstowym",
                        ),
                    ),
                    (
                        "singlelinetextinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Pole tekstowe",
                        ),
                    ),
                    (
                        "multilinetextinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Wielolinijkowe pole tekstowe",
                        ),
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="formseten",
            name="fields",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "radiobutton",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button",
                        ),
                    ),
                    (
                        "radiobuttonwithinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku radio.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button z polem tekstowym",
                        ),
                    ),
                    (
                        "radiobuttonwithmultilineinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku radio.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button z polem wielolinijkowym tekstowym",
                        ),
                    ),
                    (
                        "checkbox",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox",
                        ),
                    ),
                    (
                        "checkboxwithinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku checkbox.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox z polem tekstowym",
                        ),
                    ),
                    (
                        "checkboxwithmultilineinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku checkbox.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego.",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox z wieloninijkowym polem tekstowym",
                        ),
                    ),
                    (
                        "singlelinetextinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Pole tekstowe",
                        ),
                    ),
                    (
                        "multilinetextinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Wielolinijkowe pole tekstowe",
                        ),
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="kbcategorypage",
            name="bottom_content_box",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość dolnego bloku.",
                verbose_name="Zawartość dolnego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbcategorypage",
            name="bottom_content_box_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość dolnego bloku.",
                verbose_name="Zawartość dolnego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbcategorypage",
            name="top_content_box",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość górnego bloku.",
                verbose_name="Zawartość gównego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbcategorypage",
            name="top_content_box_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość górnego bloku.",
                verbose_name="Zawartość gównego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                default=None,
                help_text="Wprowadź treść dla tej strony.",
                verbose_name="Treść strony.",
            ),
        ),
        migrations.AlterField(
            model_name="kbpage",
            name="body_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default=None,
                help_text="Wprowadź treść dla tej strony.",
                null=True,
                verbose_name="Treść strony.",
            ),
        ),
        migrations.AlterField(
            model_name="kbrootpage",
            name="bottom_content_box",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość dolnego bloku.",
                verbose_name="Zawartość dolnego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbrootpage",
            name="bottom_content_box_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość dolnego bloku.",
                verbose_name="Zawartość dolnego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbrootpage",
            name="top_content_box",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość górnego bloku.",
                verbose_name="Zawartość gównego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbrootpage",
            name="top_content_box_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość górnego bloku.",
                verbose_name="Zawartość gównego bloku.",
            ),
        ),
    ]
