# Generated by Django 2.2.9 on 2020-11-25 14:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20201120_1548"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formset",
            name="fields",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "radiobutton",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button",
                        ),
                    ),
                    (
                        "radiobuttonwithinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button z polem tekstowym",
                        ),
                    ),
                    (
                        "radiobuttonwithmultilineinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button z wielolinijkowym polem tekstowym",
                        ),
                    ),
                    (
                        "checkbox",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox",
                        ),
                    ),
                    (
                        "checkboxwithinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox z polem tekstowym",
                        ),
                    ),
                    (
                        "checkboxwithmultilineinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox z wieloninijkowym polem tekstowym",
                        ),
                    ),
                    (
                        "singlelinetextinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Pole tekstowe",
                        ),
                    ),
                    (
                        "multilinetextinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Wielolinijkowe pole tekstowe",
                        ),
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="formseten",
            name="fields",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "radiobutton",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button",
                        ),
                    ),
                    (
                        "radiobuttonwithinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button z polem tekstowym",
                        ),
                    ),
                    (
                        "radiobuttonwithmultilineinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku radio",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Radio button z wielolinijkowym polem tekstowym",
                        ),
                    ),
                    (
                        "checkbox",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=True,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox",
                        ),
                    ),
                    (
                        "checkboxwithinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox z polem tekstowym",
                        ),
                    ),
                    (
                        "checkboxwithmultilineinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy.",
                                        label="Tekst pomocniczy dla przycisku checkbox",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "checked",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="",
                                        label="Zaznaczony domyslnie",
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_label",
                                    wagtail.core.blocks.CharBlock(
                                        label="Etykieta dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_help_text",
                                    wagtail.core.blocks.CharBlock(
                                        label="Tekst pomocniczy dla pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_default_value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość pola tekstowego",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "input_placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu do wprowadzania własnej odpowiedzi.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Checkbox z wieloninijkowym polem tekstowym",
                        ),
                    ),
                    (
                        "singlelinetextinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        label="Domyślna wartość",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Pole tekstowe",
                        ),
                    ),
                    (
                        "multilinetextinput",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Etykieta dla przycisku.",
                                        label="Etykieta",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "help_text",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst pomocniczy dla przycisku.",
                                        label="Tekst pomocniczy",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "value",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Wartość pola.",
                                        label="Wartość",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "placeholder",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Tekst wyświetlany na polu.",
                                        label="Tekst do placeholdera",
                                        max_length=5000,
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Wielolinijkowe pole tekstowe",
                        ),
                    ),
                ]
            ),
        ),
    ]
