# Generated by Django 2.2.9 on 2020-11-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0023_auto_20201126_1141"),
        ("cms", "0023_auto_20201125_1544"),
    ]

    operations = []
