# Generated by Django 2.2.9 on 2020-12-29 18:24

from django.db import migrations
import mcod.cms.blocks.common
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0025_auto_20201214_0737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kbcategorypage",
            name="bottom_content_box",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość dolnego bloku.",
                verbose_name="Zawartość dolnego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbcategorypage",
            name="bottom_content_box_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość dolnego bloku.",
                verbose_name="Zawartość dolnego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbcategorypage",
            name="top_content_box",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość górnego bloku.",
                verbose_name="Zawartość gównego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbcategorypage",
            name="top_content_box_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość górnego bloku.",
                verbose_name="Zawartość gównego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                default=None,
                help_text="Wprowadź treść dla tej strony.",
                verbose_name="Treść strony.",
            ),
        ),
        migrations.AlterField(
            model_name="kbpage",
            name="body_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default=None,
                help_text="Wprowadź treść dla tej strony.",
                null=True,
                verbose_name="Treść strony.",
            ),
        ),
        migrations.AlterField(
            model_name="kbrootpage",
            name="bottom_content_box",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość dolnego bloku.",
                verbose_name="Zawartość dolnego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbrootpage",
            name="bottom_content_box_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość dolnego bloku.",
                verbose_name="Zawartość dolnego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbrootpage",
            name="top_content_box",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość górnego bloku.",
                verbose_name="Zawartość gównego bloku.",
            ),
        ),
        migrations.AlterField(
            model_name="kbrootpage",
            name="top_content_box_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "h2",
                                "h3",
                                "h4",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                                "subscript",
                                "strikethroughdocument-link",
                                "lang-pl",
                                "lang-en",
                            ],
                            label="Tekst",
                        ),
                    ),
                    ("raw_html", mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML")),
                    ("image", mcod.cms.blocks.common.ImageChooserBlock(label="Obraz")),
                ],
                blank=True,
                default="",
                help_text="Wprowadź zawartość górnego bloku.",
                verbose_name="Zawartość gównego bloku.",
            ),
        ),
    ]
