# Generated by Django 2.2.9 on 2020-12-29 13:50

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0025_auto_20201214_0737"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="i18n",
            field=modeltrans.fields.TranslationField(fields=("alt",), required_languages=(), virtual_fields=True),
        ),
    ]
