# Generated by Django 2.2.9 on 2021-01-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0026_auto_20201229_1924"),
        ("cms", "0026_customimage_i18n"),
    ]

    operations = []
