# Generated by Django 2.2.9 on 2021-01-21 20:52

from django.db import migrations
import mcod.cms.blocks.common
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0028_auto_20210114_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootpage",
            name="over_search_field_cb",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "cta",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                mcod.cms.blocks.common.ImageChooserBlock(
                                                    help_text="Obraz tła może być również animowanym gifem. Zalecany rozmiar: 1920 x 340 pikseli.",
                                                    label="Obraz w tle",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "color",
                                                mcod.cms.blocks.common.ColorPickerBlock(
                                                    default="#ffffff",
                                                    help_text="Kolor tła będzie zawsze pod spodem wszystkich innych elementów bloku (w tym również obrazu tła).",
                                                    label="Kolor tła",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "paralax",
                                                wagtail.core.blocks.BooleanBlock(
                                                    default=False,
                                                    help_text="Przy włączonym efekcie paralaksy tło przewija się wolniej niż pozostałe elementy strony, co tworzy wrażenie głębi.",
                                                    label="Efekt paralaksy",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Tło bloku",
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                mcod.cms.blocks.common.ImageChooserBlock(
                                                    help_text="Obrazek, który będzie wyświetlany obok tekstu. Zalecany rozmiar: 1920 x 340 pikseli.",
                                                    label="Obrazek",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "position",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("left", "od lewej"),
                                                        ("center", "na środku"),
                                                        ("right", "od prawej"),
                                                    ],
                                                    help_text="\n                                Położenie obrazka względem tytułu oraz tekstu.\n                                ",
                                                    label="Położenie",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Obraz obok tekstu",
                                    ),
                                ),
                                (
                                    "header",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    help_text="Maksymalnie 20 znaków.",
                                                    label="Tytuł",
                                                    max_length=20,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "align",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("left", "od lewej"),
                                                        ("center", "na środku"),
                                                        ("right", "od prawej"),
                                                    ],
                                                    help_text="\n                                    Określa położenie tekstu w bloku.\n                                    ",
                                                    label="Wyrównanie",
                                                ),
                                            ),
                                        ],
                                        label="Tytuł",
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.TextBlock(
                                                    help_text="Treść tekstu wyświetlanego pod tytułem. Maksymalnie 4 linie, 200 znaków.",
                                                    label="Tekst",
                                                    max_length=200,
                                                    required=False,
                                                    rows=4,
                                                ),
                                            ),
                                            (
                                                "align",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("left", "od lewej"),
                                                        ("center", "na środku"),
                                                        ("right", "od prawej"),
                                                    ],
                                                    help_text="Określa położenie tekstu w bloku.",
                                                    label="Wyrównanie",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Tekst pod tytułem",
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    help_text="Maksymalnie 20 znaków.",
                                                    label="Tekst na przycisku",
                                                    max_length=20,
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "position",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("left", "od lewej"),
                                                        ("center", "na środku"),
                                                        ("right", "od prawej"),
                                                    ],
                                                    label="Położenie",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "size",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("btn-normal", "Normalny"),
                                                        ("btn-sm", "Mały"),
                                                        ("btn-lg", "Duży"),
                                                    ],
                                                    label="Rozmiar",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "style",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("btn-primary", "Niebieski"),
                                                        ("btn-secondary", "Szary"),
                                                        ("btn-success", "Zielony"),
                                                        ("btn-danger", "Czerwony"),
                                                        ("btn-warning", "Żółty"),
                                                        ("btn-info", "Turkusowy"),
                                                        ("btn-light", "Jasny"),
                                                        ("btn-dark", "Ciemny"),
                                                        ("btn-link", "Link"),
                                                    ],
                                                    label="Styl",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "action_url",
                                                wagtail.core.blocks.URLBlock(
                                                    help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu przycisku.",
                                                    label="Adres URL",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "target",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("_self", "To samo okno"),
                                                        ("_blank", "Nowe okno"),
                                                    ],
                                                    help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                                    label="Cel",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Przycisk",
                                    ),
                                ),
                            ],
                            label="Call To Action",
                            required=False,
                        ),
                    ),
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                            required=False,
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                            required=False,
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(label="Tekst sformatowany", required=False),
                    ),
                    (
                        "raw_html",
                        mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML", required=False),
                    ),
                    (
                        "svg",
                        mcod.cms.blocks.common.SvgDocumentChooserBlock(label="Obraz SVG", required=False),
                    ),
                    (
                        "image",
                        mcod.cms.blocks.common.ImageChooserBlock(label="Obrazek", required=False),
                    ),
                ],
                blank=True,
                default=None,
                help_text="TODO: napisać",
                verbose_name="Blok pod wyszukiwarką",
            ),
        ),
        migrations.AlterField(
            model_name="rootpage",
            name="over_search_field_cb_en",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "cta",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                mcod.cms.blocks.common.ImageChooserBlock(
                                                    help_text="Obraz tła może być również animowanym gifem. Zalecany rozmiar: 1920 x 340 pikseli.",
                                                    label="Obraz w tle",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "color",
                                                mcod.cms.blocks.common.ColorPickerBlock(
                                                    default="#ffffff",
                                                    help_text="Kolor tła będzie zawsze pod spodem wszystkich innych elementów bloku (w tym również obrazu tła).",
                                                    label="Kolor tła",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "paralax",
                                                wagtail.core.blocks.BooleanBlock(
                                                    default=False,
                                                    help_text="Przy włączonym efekcie paralaksy tło przewija się wolniej niż pozostałe elementy strony, co tworzy wrażenie głębi.",
                                                    label="Efekt paralaksy",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Tło bloku",
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                mcod.cms.blocks.common.ImageChooserBlock(
                                                    help_text="Obrazek, który będzie wyświetlany obok tekstu. Zalecany rozmiar: 1920 x 340 pikseli.",
                                                    label="Obrazek",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "position",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("left", "od lewej"),
                                                        ("center", "na środku"),
                                                        ("right", "od prawej"),
                                                    ],
                                                    help_text="\n                                Położenie obrazka względem tytułu oraz tekstu.\n                                ",
                                                    label="Położenie",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Obraz obok tekstu",
                                    ),
                                ),
                                (
                                    "header",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    help_text="Maksymalnie 20 znaków.",
                                                    label="Tytuł",
                                                    max_length=20,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "align",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("left", "od lewej"),
                                                        ("center", "na środku"),
                                                        ("right", "od prawej"),
                                                    ],
                                                    help_text="\n                                    Określa położenie tekstu w bloku.\n                                    ",
                                                    label="Wyrównanie",
                                                ),
                                            ),
                                        ],
                                        label="Tytuł",
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.TextBlock(
                                                    help_text="Treść tekstu wyświetlanego pod tytułem. Maksymalnie 4 linie, 200 znaków.",
                                                    label="Tekst",
                                                    max_length=200,
                                                    required=False,
                                                    rows=4,
                                                ),
                                            ),
                                            (
                                                "align",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("left", "od lewej"),
                                                        ("center", "na środku"),
                                                        ("right", "od prawej"),
                                                    ],
                                                    help_text="Określa położenie tekstu w bloku.",
                                                    label="Wyrównanie",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Tekst pod tytułem",
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.core.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.core.blocks.CharBlock(
                                                    help_text="Maksymalnie 20 znaków.",
                                                    label="Tekst na przycisku",
                                                    max_length=20,
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "position",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("left", "od lewej"),
                                                        ("center", "na środku"),
                                                        ("right", "od prawej"),
                                                    ],
                                                    label="Położenie",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "size",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("btn-normal", "Normalny"),
                                                        ("btn-sm", "Mały"),
                                                        ("btn-lg", "Duży"),
                                                    ],
                                                    label="Rozmiar",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "style",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("btn-primary", "Niebieski"),
                                                        ("btn-secondary", "Szary"),
                                                        ("btn-success", "Zielony"),
                                                        ("btn-danger", "Czerwony"),
                                                        ("btn-warning", "Żółty"),
                                                        ("btn-info", "Turkusowy"),
                                                        ("btn-light", "Jasny"),
                                                        ("btn-dark", "Ciemny"),
                                                        ("btn-link", "Link"),
                                                    ],
                                                    label="Styl",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "action_url",
                                                wagtail.core.blocks.URLBlock(
                                                    help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu przycisku.",
                                                    label="Adres URL",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "target",
                                                wagtail.core.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("_self", "To samo okno"),
                                                        ("_blank", "Nowe okno"),
                                                    ],
                                                    help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                                    label="Cel",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="Przycisk",
                                    ),
                                ),
                            ],
                            label="Call To Action",
                            required=False,
                        ),
                    ),
                    (
                        "banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    mcod.cms.blocks.common.ImageChooserBlock(
                                        help_text="\n                                Obrazek bannera. Zalecany rozmiar: 1920 x 340 pikseli.\n                                ",
                                        label="Obrazek",
                                        required=True,
                                    ),
                                ),
                                (
                                    "action_url",
                                    wagtail.core.blocks.URLBlock(
                                        help_text="Strona, na którą zostanie przekierowany użytkownik po naciśnięciu na baner.",
                                        label="Adres URL",
                                        required=True,
                                    ),
                                ),
                                (
                                    "target",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("_self", "To samo okno"),
                                            ("_blank", "Nowe okno"),
                                        ],
                                        help_text='Cel określa, czy strona w polu "Adres URL" ma się otwierać w tym samym, czy też w nowym oknie.',
                                        label="Cel",
                                        required=False,
                                    ),
                                ),
                            ],
                            label="Baner reklamowy",
                            required=False,
                        ),
                    ),
                    (
                        "video",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "video",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="Wklej adres URL do wideo, na przykład: https://www.youtube.com/watch?v=jVAYxah_RP8",
                                        label="Wideo",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.core.blocks.TextBlock(
                                        help_text="Opcjonalny podpis filmu, dwie linie, maksymalnie 60 znaków.",
                                        label="Podpis",
                                        max_length=60,
                                        required=False,
                                        rows=2,
                                    ),
                                ),
                            ],
                            label="Film",
                            required=False,
                        ),
                    ),
                    (
                        "text",
                        mcod.cms.blocks.common.RichTextBlock(label="Tekst sformatowany", required=False),
                    ),
                    (
                        "raw_html",
                        mcod.cms.blocks.common.RawHTMLBlock(label="Kod HTML", required=False),
                    ),
                    (
                        "svg",
                        mcod.cms.blocks.common.SvgDocumentChooserBlock(label="Obraz SVG", required=False),
                    ),
                    (
                        "image",
                        mcod.cms.blocks.common.ImageChooserBlock(label="Obrazek", required=False),
                    ),
                ],
                blank=True,
                default=None,
                help_text="TODO: napisać",
                verbose_name="Blok pod wyszukiwarką",
            ),
        ),
    ]
