# Generated by Django 2.2.9 on 2022-04-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0034_auto_20220222_1335"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rootpage",
            name="header_gov",
        ),
        migrations.RemoveField(
            model_name="rootpage",
            name="header_gov_en",
        ),
    ]
