# Generated by Django 2.2 on 2019-10-09 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mcod.harvester.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0009_auto_20190604_2022"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                ("portal_url", models.URLField(verbose_name="portal url")),
                ("api_url", models.URLField(verbose_name="api url")),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "every day"),
                            (7, "every week"),
                            (30, "every month"),
                            (90, "every quarter"),
                        ],
                        default=7,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        max_length=8,
                        verbose_name="status",
                    ),
                ),
                ("data_use_rules", models.TextField(verbose_name="data use rules")),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("local", "Local goverment"),
                            ("state", "Public goverment"),
                            ("other", "Other"),
                        ],
                        max_length=5,
                        verbose_name="institution type",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("ckan", "CKAN")],
                        max_length=10,
                        verbose_name="source type",
                    ),
                ),
                (
                    "emails",
                    models.TextField(
                        validators=[mcod.harvester.models.validate_emails_list],
                        verbose_name="e-mail",
                    ),
                ),
                (
                    "last_activation_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="last activation date"),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="creation date",
                    ),
                ),
                (
                    "last_import_status",
                    models.CharField(
                        blank=True,
                        choices=[("ok", "OK"), ("error", "Error")],
                        max_length=5,
                        verbose_name="last import status",
                    ),
                ),
                (
                    "last_import_timestamp",
                    models.DateTimeField(blank=True, null=True, verbose_name="last import timestamp"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_datasources",
                        to="categories.Category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_datasources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "data source",
                "verbose_name_plural": "data sources",
            },
        ),
        migrations.CreateModel(
            name="DataSourceImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="start")),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="end"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("ok", "OK"), ("error", "Error")],
                        max_length=5,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_desc",
                    models.TextField(blank=True, verbose_name="error description"),
                ),
                (
                    "datasets_count",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="number of imported datasets",
                    ),
                ),
                (
                    "resources_count",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="number of imported resources",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="harvester.DataSource",
                        verbose_name="data source",
                    ),
                ),
            ],
            options={
                "verbose_name": "data source import",
                "verbose_name_plural": "data source imports",
            },
        ),
        migrations.CreateModel(
            name="DataSourceTrash",
            fields=[],
            options={
                "verbose_name": "Trash",
                "verbose_name_plural": "Trash",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("harvester.datasource",),
        ),
    ]
