# Generated by Django 2.2 on 2019-10-11 10:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="datasource",
            managers=[
                ("raw", django.db.models.manager.Manager()),
            ],
        ),
    ]
