# Generated by Django 2.2 on 2019-10-15 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("harvester", "0002_auto_20191011_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="modified_datasources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="modified by",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_datasources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
