# Generated by Django 2.2 on 2019-10-25 07:54
import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0004_auto_20191017_0947"),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(os.path.join(settings.DATABASE_DIR, "MCOD-1519-harvester-history_other.sql")).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "MCOD-1519-harvester-history_other_backward.sql",
                )
            ).read(),
        )
    ]
