# Generated by Django 2.2 on 2020-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0007_auto_20191120_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="license_condition_db_or_copyrighted",
            field=models.TextField(blank=True, verbose_name="data use rules"),
        ),
    ]
