# Generated by Django 2.2.9 on 2020-02-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('organizations', '0012_auto_20190604_2022'),
        ("harvester", "0008_auto_20200108_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_datasources",
                to="organizations.Organization",
                verbose_name="Institution",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="source_hash",
            field=models.CharField(blank=True, max_length=32, verbose_name="source hash"),
        ),
        migrations.AddField(
            model_name="datasource",
            name="xml_url",
            field=models.URLField(blank=True, verbose_name="XML url"),
        ),
        migrations.AddField(
            model_name="datasourceimport",
            name="datasets_updated_count",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="number of updated datasets"),
        ),
        migrations.AddField(
            model_name="datasourceimport",
            name="is_report_email_sent",
            field=models.BooleanField(default=False, verbose_name="Is report email sent?"),
        ),
        migrations.AddField(
            model_name="datasourceimport",
            name="resources_updated_count",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="number of updated resources"),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="api_url",
            field=models.URLField(blank=True, verbose_name="api url"),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_datasources",
                to="categories.Category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="institution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("local", "Local goverment"),
                    ("state", "Public goverment"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=5,
                verbose_name="Default type for newly created institutions",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="portal_url",
            field=models.URLField(blank=True, verbose_name="portal url"),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="source_type",
            field=models.CharField(
                choices=[("ckan", "CKAN"), ("xml", "XML")],
                max_length=10,
                verbose_name="source type",
            ),
        ),
    ]
