# Generated by Django 2.2.9 on 2021-02-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_datamigration_create_basic_dcat_categories"),
        ("harvester", "0009_auto_20200210_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                db_table="data_source_category",
                limit_choices_to=models.Q(_negated=True, code=""),
                related_name="data_sources",
                related_query_name="data_source",
                to="categories.Category",
                verbose_name="Categories",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(code=""),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_datasources",
                to="categories.Category",
                verbose_name="category",
            ),
        ),
    ]
