# Generated by Django 2.2.9 on 2021-03-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0012_auto_20210323_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="institution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("local", "Local government"),
                    ("state", "Public government"),
                    ("private", "Private entities"),
                    ("other", "Other"),
                ],
                default="private",
                max_length=7,
                verbose_name="Default type for newly created institutions",
            ),
        ),
    ]
