# Generated by Django 2.2.9 on 2021-05-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0014_datasource_is_permanently_removed"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="datasource",
            managers=[],
        ),
    ]
