# Generated by Django 2.2.9 on 2021-05-19 09:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0015_auto_20210517_1732"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasource",
            options={
                "default_manager_name": "raw",
                "verbose_name": "data source",
                "verbose_name_plural": "data sources",
            },
        ),
        migrations.AlterModelManagers(
            name="datasource",
            managers=[
                ("raw", django.db.models.manager.Manager()),
            ],
        ),
    ]
