# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0017_auto_20210531_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="description",
            field=mcod.lib.model_sanitization.SanitizedTextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="name",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=255, verbose_name="name"),
        ),
    ]
