# Generated by Django 2.2.9 on 2025-09-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0018_auto_20241029_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="institution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("local", "Local government"),
                    ("state", "Public government"),
                    ("private", "Private entities"),
                    ("developer", "Developers"),
                    ("other", "Other"),
                ],
                default="private",
                max_length=9,
                verbose_name="Default type for newly created institutions",
            ),
        ),
    ]
