# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_auto_20190208_0933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="description",
            field=mcod.lib.model_sanitization.SanitizedTextField(
                help_text="Description of the alert", verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="i18n",
            field=mcod.lib.model_sanitization.SanitizedTranslationField(
                fields=("title", "description"), required_languages=("pl",), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(
                help_text="Title of the alert (300 characters max.)", max_length=300, verbose_name="Title"
            ),
        ),
    ]
