json = {
    "attrs": {
        "Figure": {
            "background_fill_color": "#000000",
            "border_fill_color": "#000000",
            "outline_line_color": "#FFFFFF",
            "outline_line_alpha": 0,
        },
        "Grid": {"grid_line_color": "#FFFFFF", "grid_line_alpha": 1},
        "Axis": {
            "major_tick_line_alpha": 1,
            "major_tick_line_color": "#FFFFFF",
            "minor_tick_line_alpha": 1,
            "minor_tick_line_color": "#FFFFFF",
            "axis_line_alpha": 1,
            "axis_line_color": "#FFFFFF",
            "major_label_text_color": "#FFFFFF",
            "major_label_text_font": "Helvetica",
            "major_label_text_font_size": "1.025em",
            "axis_label_standoff": 10,
            "axis_label_text_color": "#FFFFFF",
            "axis_label_text_font": "Helvetica",
            "axis_label_text_font_size": "1.25em",
            "axis_label_text_font_style": "normal",
        },
        "Legend": {
            "spacing": 8,
            "glyph_width": 15,
            "label_standoff": 8,
            "label_text_color": "#FFFFFF",
            "label_text_font": "Helvetica",
            "label_text_font_size": "1.025em",
            "border_line_alpha": 0,
            "background_fill_alpha": 0.25,
            "background_fill_color": "black",
        },
        "ColorBar": {
            "title_text_color": "#FFFFFF",
            "title_text_font": "Helvetica",
            "title_text_font_size": "1.025em",
            "title_text_font_style": "normal",
            "major_label_text_color": "#FFFFFF",
            "major_label_text_font": "Helvetica",
            "major_label_text_font_size": "1.025em",
            "background_fill_color": "#FFFFFF",
            "major_tick_line_alpha": 1,
            "bar_line_alpha": 1,
        },
        "Title": {
            "text_color": "#FFFFFF",
            "text_font": "Helvetica",
            "text_font_size": "1.15em",
        },
    }
}
