# Generated by Django 2.0.4 on 2018-04-26 09:53

from django.db import migrations, models
import django.utils.timezone
import mcod.core.storages
import model_utils.fields
import django.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "slug",
                    models.CharField(max_length=254, unique=True, verbose_name="Name"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=254,
                        null=True,
                        storage=mcod.core.storages.OrganizationImagesStorage(base_url=None, location=None),
                        upload_to="%Y%m%d",
                        verbose_name="Image URL",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=6, null=True, verbose_name="Postal code"),
                ),
                (
                    "city",
                    models.CharField(max_length=200, null=True, verbose_name="City"),
                ),
                (
                    "street_type",
                    models.CharField(max_length=50, null=True, verbose_name="Street type"),
                ),
                (
                    "street",
                    models.CharField(max_length=200, null=True, verbose_name="Street"),
                ),
                (
                    "street_number",
                    models.CharField(
                        max_length=200,
                        null=True,
                        blank=True,
                        verbose_name="Street number",
                    ),
                ),
                (
                    "flat_number",
                    models.CharField(
                        max_length=200,
                        null=True,
                        blank=True,
                        verbose_name="Flat number",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=300, null=True, verbose_name="Email"),
                ),
                (
                    "epuap",
                    models.CharField(max_length=500, null=True, verbose_name="EPUAP"),
                ),
                ("fax", models.CharField(max_length=50, null=True, verbose_name="Fax")),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("local", "Local goverment"),
                            ("state", "Public goverment"),
                            ("other", "Other"),
                        ],
                        default="state",
                        max_length=50,
                        verbose_name="Institution type",
                    ),
                ),
                (
                    "regon",
                    models.CharField(max_length=20, null=True, verbose_name="REGON"),
                ),
                (
                    "tel",
                    models.CharField(max_length=50, null=True, verbose_name="Phone"),
                ),
                (
                    "website",
                    models.CharField(max_length=200, null=True, verbose_name="Website"),
                ),
            ],
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
                "db_table": "organization",
            },
        ),
    ]
