# Generated by Django 2.0.4 on 2019-01-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_auto_20180625_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="fax_internal",
            field=models.CharField(max_length=20, null=True, blank=True, verbose_name="int."),
        ),
        migrations.AddField(
            model_name="organization",
            name="tel_internal",
            field=models.CharField(max_length=20, null=True, blank=True, verbose_name="int."),
        ),
    ]
