# Generated by Django 2.1.4 on 2019-02-27 10:08

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_organization_i18n"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("slug", "title", "description", "city"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.CharField(max_length=254, unique=True, verbose_name="Slug"),
        ),
    ]
