# Generated by Django 2.2 on 2019-04-10 12:41

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import modeltrans.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_auto_20190227_1108"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="published_at",
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor="status", when={"published"}),
        ),
        migrations.AddField(
            model_name="organization",
            name="removed_at",
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor="is_removed", when={True}),
        ),
        migrations.AddField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="organization",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="organization",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("title", "description", "slug"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, default=uuid.uuid4, max_length=600),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="organizatio_i18n_f57983_gin"),
        ),
    ]
