# Generated by Django 2.2 on 2019-05-08 13:00

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_auto_20190507_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("title", "description", "slug"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
