# Generated by Django 2.2.9 on 2020-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_auto_20190604_2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="abbreviation",
            field=models.CharField(max_length=10, null=True, verbose_name="Abbreviation"),
        ),
    ]
