# Generated by Django 2.2.9 on 2021-03-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_auto_20200417_0907"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="institution_type",
            field=models.CharField(
                choices=[
                    ("local", "Local government"),
                    ("state", "Public government"),
                    ("private", "Private entities"),
                    ("other", "Other"),
                ],
                default="state",
                max_length=50,
                verbose_name="Institution type",
            ),
        ),
    ]
