# Generated by Django 2.2.9 on 2021-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0015_auto_20210326_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_permanently_removed",
            field=models.BooleanField(default=False),
        ),
    ]
