# Generated by Django 2.2.9 on 2021-12-01 10:49
import os

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_auto_20210530_1758"),
        ("resources", "0048_resource_regions"),  # newest resource's migration at now.
    ]
    operations = [
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2225-daily-report-with-new-counters-backward.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2225-daily-report-with-new-counters.sql",
                )
            ).read(),
        ),
        migrations.RunSQL(
            sql="DROP MATERIALIZED VIEW IF EXISTS public.mv_resource_dataset_organization_report;DROP FUNCTION IF EXISTS fn_refresh_mv_resource_dataset_organization_report();",
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2126-converted-formats-in-daily-report.sql",
                )
            ).read(),
        ),
        migrations.AlterField(
            model_name="organization",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2126-converted-formats-in-daily-report.sql",
                )
            ).read(),
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS public.mv_resource_dataset_organization_report;DROP FUNCTION IF EXISTS fn_refresh_mv_resource_dataset_organization_report();",
        ),
        migrations.RunSQL(
            sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2225-daily-report-with-new-counters.sql",
                )
            ).read(),
            reverse_sql=open(
                os.path.join(
                    settings.DATABASE_DIR,
                    "ODSOFT-2225-daily-report-with-new-counters-backward.sql",
                )
            ).read(),
        ),
    ]
