# Generated by Django 2.2.9 on 2024-03-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_auto_20211201_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="electronic_delivery_address",
            field=models.CharField(
                blank=True,
                max_length=26,
                null=True,
                unique=True,
                verbose_name="Address for electronic delivery",
            ),
        ),
    ]
