# Generated by Django 2.2.9 on 2024-04-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_auto_20240325_1922"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, electronic_delivery_address=""),
                name="electronic_delivery_address_not_empty_string",
            ),
        ),
    ]
