# Generated by Django 2.2.9 on 2024-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_auto_20240403_1138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="electronic_delivery_address",
            field=models.CharField(
                blank=True,
                max_length=26,
                null=True,
                verbose_name="Address for electronic delivery",
            ),
        ),
    ]
