# Generated by Django 2.2.9 on 2024-10-29 14:08

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0022_auto_20240529_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="abbreviation",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=30, null=True, verbose_name="Abbreviation"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="city",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=200, null=True, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=mcod.lib.model_sanitization.SanitizedTextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="epuap",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=500, null=True, verbose_name="EPUAP"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="flat_number",
            field=mcod.lib.model_sanitization.SanitizedCharField(
                blank=True, max_length=200, null=True, verbose_name="Flat number"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="i18n",
            field=mcod.lib.model_sanitization.SanitizedTranslationField(
                fields=("title", "description", "slug"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="street",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=200, null=True, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="street_number",
            field=mcod.lib.model_sanitization.SanitizedCharField(
                blank=True, max_length=200, null=True, verbose_name="Street number"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="street_type",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=50, null=True, verbose_name="Street type"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(max_length=200, verbose_name="Name"),
        ),
    ]
