# Generated by Django 2.2.9 on 2025-09-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_auto_20241029_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="institution_type",
            field=models.CharField(
                choices=[
                    ("local", "Local government"),
                    ("state", "Public government"),
                    ("private", "Private entities"),
                    ("developer", "Developers"),
                    ("other", "Other"),
                ],
                default="state",
                max_length=50,
                verbose_name="Institution type",
            ),
        ),
    ]
