# Generated by Django 2.2.9 on 2025-10-10 10:48

from django.db import migrations
import mcod.core.model_validators
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_auto_20250903_0912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=mcod.lib.model_sanitization.SanitizedTextField(
                blank=True,
                null=True,
                validators=[mcod.core.model_validators.illegal_character_validator],
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="title",
            field=mcod.lib.model_sanitization.SanitizedCharField(
                max_length=200, validators=[mcod.core.model_validators.illegal_character_validator], verbose_name="Name"
            ),
        ),
    ]
